// Generated by crawler/src/extract.ts — do not edit by hand.
import type { StatementData } from "@/lib/types"

// The report PDFs these numbers were extracted from.
export const sources = [
  {
    "year": 2025,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2026-02/airbus_fy_2025_financial_statements_1.pdf"
  },
  {
    "year": 2024,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2025-04/Airbus%20Financial%20Statements%202024%20%281%29.pdf"
  },
  {
    "year": 2023,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2024-03/Airbus-Financial-Statements-FY2023.pdf"
  },
  {
    "year": 2022,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2023-05/Airbus_Financial_Statements_FY_2022.pdf"
  },
  {
    "year": 2021,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2022-03/AIRBUS%20FY2021%20FINANCIAL%20STATEMENTS%20DS.pdf"
  },
  {
    "year": 2020,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2021-06/AIRBUS_FINANCIAL_STATEMENTS_2020.pdf"
  },
  {
    "year": 2019,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2021-07/Airbus-LG-Financial-Statements-2019.pdf"
  },
  {
    "year": 2018,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2021-07/Airbus-SE-Financial-Statements-2018.pdf"
  },
  {
    "year": 2017,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2021-07/Airbus-SE-Financial-Statements-2017_0.pdf"
  },
  {
    "year": 2016,
    "url": "https://www.airbus.com/sites/g/files/jlcbta136/files/2021-06/airbus-financial-statements-2016.pdf"
  }
]

// Cross-statement validation result (accounting identities) at extraction time.
export const validation = {
  "status": "fail",
  "issues": [
    {
      "check": "balance: no total assets value (wrong page?)",
      "severity": "fail",
      "period": "31 December 2016",
      "expected": 0,
      "actual": 0,
      "diff": 0
    },
    {
      "check": "balance: no total assets value (wrong page?)",
      "severity": "fail",
      "period": "31 December 2015",
      "expected": 0,
      "actual": 0,
      "diff": 0
    }
  ]
} as const

export const incomeStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016"
  ],
  "rows": [
    {
      "label": "Revenue",
      "kind": "line",
      "values": [
        73420,
        69230,
        65446,
        58763,
        52149,
        49912,
        70478,
        63707,
        66767,
        66581
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Cost of sales",
      "kind": "line",
      "values": [
        -62453,
        -58555,
        -55402,
        -48192,
        -42518,
        -44250,
        -59973,
        -54920,
        -59160,
        -61317
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Gross margin",
      "kind": "line",
      "values": [
        10967,
        10675,
        10044,
        10571,
        9631,
        5662,
        10505,
        8787,
        7607,
        5264
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Selling expenses",
      "kind": "line",
      "values": [
        -856,
        -877,
        -867,
        -788,
        -713,
        -717,
        -908,
        -861,
        -872,
        -997
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Administrative expenses",
      "kind": "line",
      "values": [
        -1722,
        -1744,
        -1654,
        -1452,
        -1339,
        -1423,
        -5217,
        -1574,
        -1567,
        -1726
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Research and development expenses",
      "kind": "line",
      "values": [
        -3153,
        -3250,
        -3257,
        -3079,
        -2746,
        -2858,
        -3358,
        -3217,
        -2807,
        -2970
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Other income",
      "kind": "line",
      "values": [
        979,
        303,
        243,
        471,
        594,
        132,
        370,
        1656,
        981,
        2689
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Other expenses",
      "kind": "line",
      "values": [
        -488,
        -197,
        -209,
        -590,
        -201,
        -1458,
        -356,
        -182,
        -336,
        -254
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Share of profit from investments accounted for under the equity method",
      "kind": "line",
      "values": [
        305,
        350,
        267,
        134,
        40,
        39,
        299,
        330,
        333,
        231
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Other income from investments",
      "kind": "line",
      "values": [
        50,
        44,
        36,
        58,
        76,
        113,
        4,
        109,
        82,
        21
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Profit before financial result and income taxes",
      "kind": "line",
      "values": [
        6082,
        5304,
        4603,
        5325,
        5342,
        null,
        1339,
        5048,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Interest income",
      "kind": "line",
      "values": [
        710,
        802,
        728,
        180,
        88,
        140,
        228,
        208,
        189,
        247
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Interest expense",
      "kind": "line",
      "values": [
        -770,
        -900,
        -753,
        -412,
        -334,
        -411,
        -339,
        -440,
        -517,
        -522
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Other financial result",
      "kind": "line",
      "values": [
        328,
        219,
        191,
        -18,
        -69,
        -349,
        -164,
        -531,
        1477,
        -692
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Total financial result",
      "kind": "line",
      "values": [
        268,
        121,
        166,
        -250,
        -315,
        -620,
        -275,
        -763,
        1149,
        -967
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Income taxes",
      "kind": "line",
      "values": [
        -1390,
        -1347,
        -1156,
        -939,
        -853,
        -39,
        -2389,
        -1274,
        -1693,
        -291
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Profit for the period",
      "kind": "line",
      "values": [
        4960,
        4078,
        3613,
        4136,
        4174,
        null,
        null,
        null,
        2877,
        1000
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Attributable to:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Equity owners of the parent (Net Income)",
      "kind": "line",
      "values": [
        5221,
        4232,
        3789,
        4247,
        4213,
        -1133,
        -1362,
        3054,
        2873,
        995
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Non-controlling interests",
      "kind": "line",
      "values": [
        -261,
        -154,
        -176,
        -111,
        -39,
        -36,
        -43,
        null,
        4,
        5
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Earnings per share",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Basic",
      "kind": "line",
      "values": [
        6.61,
        5.36,
        4.8,
        5.4,
        5.36,
        -1.45,
        -1.75,
        3.94,
        3.71,
        1.29
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Diluted",
      "kind": "line",
      "values": [
        6.6,
        5.35,
        4.8,
        5.39,
        5.36,
        -1.45,
        -1.75,
        3.92,
        3.7,
        1.29
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Profit (Loss) before financial result and income taxes",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        5342,
        -510,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Profit (Loss) for the period",
      "kind": "total",
      "values": [
        null,
        null,
        null,
        null,
        4174,
        -1169,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "(Loss) Profit for the period",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -1325,
        3011,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Other comprehensive income",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Items that will not be reclassified to profit or loss:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Remeasurement of the defined benefit pension plans",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -2669,
        -552,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Change in fair value of financial assets",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        267,
        -249,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Share of change from investments accounted for under the equity method",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -130,
        3,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Income tax relating to items that will not be reclassified",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        410,
        -2,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Items that may be reclassified to profit or loss:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Foreign currency translation differences for foreign operations",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        54,
        108,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Change in fair value of cash flow hedges",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -1434,
        -2959,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Income tax relating to items that may be reclassified",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        342,
        728,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Other comprehensive income, net of tax",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -3021,
        -3014,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Total comprehensive income for the period",
      "kind": "total",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -4346,
        -3,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Equity owners of the parent",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -4364,
        72,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Profit before finance costs and income taxes",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        3421,
        2258
      ]
    }
  ]
}

export const balanceSheet: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "31 December 2016",
    "31 December 2015"
  ],
  "rows": [
    {
      "label": "Assets",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Non-current assets",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Intangible assets",
      "kind": "line",
      "values": [
        16847,
        17179,
        16929,
        16768,
        16367,
        16199,
        16591,
        16726,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Property, plant and equipment",
      "kind": "line",
      "values": [
        20893,
        19112,
        17201,
        16505,
        16536,
        16674,
        17294,
        16773,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Investment property",
      "kind": "line",
      "values": [
        35,
        35,
        37,
        41,
        2,
        2,
        2,
        3,
        null,
        null
      ],
      "restatedIndices": [
        6
      ]
    },
    {
      "label": "Investments accounted for under the equity method",
      "kind": "line",
      "values": [
        2360,
        2433,
        2228,
        2067,
        1672,
        1578,
        1626,
        1693,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Other investments and other long-term financial assets",
      "kind": "line",
      "values": [
        5470,
        5077,
        4719,
        4190,
        4001,
        3855,
        4453,
        3811,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Non-current contract assets",
      "kind": "line",
      "values": [
        17,
        61,
        26,
        26,
        27,
        48,
        91,
        65,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Non-current other financial assets",
      "kind": "line",
      "values": [
        1070,
        697,
        922,
        781,
        691,
        3483,
        1033,
        1108,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Non-current other assets",
      "kind": "line",
      "values": [
        2762,
        2650,
        1854,
        1872,
        901,
        483,
        522,
        888,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Deferred tax assets",
      "kind": "line",
      "values": [
        1808,
        3505,
        3448,
        4683,
        4323,
        4023,
        5008,
        4835,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Non-current securities",
      "kind": "line",
      "values": [
        9997,
        9032,
        7508,
        6013,
        6794,
        5350,
        11066,
        10662,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Total non-current assets",
      "kind": "subtotal",
      "values": [
        61292,
        59781,
        54870,
        52942,
        51353,
        51695,
        57686,
        56564,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Current assets",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Inventories",
      "kind": "line",
      "values": [
        41676,
        37745,
        33741,
        32202,
        28538,
        30401,
        31550,
        31891,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Trade receivables",
      "kind": "line",
      "values": [
        5454,
        5293,
        4725,
        4953,
        4957,
        5132,
        5674,
        6078,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Current portion of other long-term financial assets",
      "kind": "line",
      "values": [
        734,
        897,
        795,
        665,
        537,
        468,
        449,
        489,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Current contract assets",
      "kind": "line",
      "values": [
        1639,
        1474,
        1823,
        1501,
        1377,
        1074,
        1167,
        789,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Current other financial assets",
      "kind": "line",
      "values": [
        2557,
        2004,
        1851,
        2542,
        1451,
        2432,
        2060,
        1811,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Current other assets",
      "kind": "line",
      "values": [
        3760,
        3463,
        2697,
        2850,
        2393,
        2216,
        2423,
        4246,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Current tax assets",
      "kind": "line",
      "values": [
        543,
        663,
        546,
        704,
        552,
        620,
        1784,
        1451,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Current securities",
      "kind": "line",
      "values": [
        3093,
        2829,
        1301,
        1762,
        1317,
        1618,
        2302,
        2132,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Cash and cash equivalents",
      "kind": "line",
      "values": [
        14128,
        15003,
        16469,
        15823,
        14572,
        14439,
        9314,
        9413,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Total current assets",
      "kind": "subtotal",
      "values": [
        73584,
        69371,
        63948,
        63002,
        55694,
        58400,
        56723,
        58300,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Assets and disposal group of assets classified as held for sale",
      "kind": "line",
      "values": [
        63,
        61,
        53,
        0,
        0,
        0,
        0,
        334,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        4,
        5,
        6
      ]
    },
    {
      "label": "Total assets",
      "kind": "total",
      "values": [
        134939,
        129213,
        118871,
        115944,
        107047,
        110095,
        114409,
        115198,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Equity and liabilities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Equity attributable to owners of the parent",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Capital stock",
      "kind": "line",
      "values": [
        793,
        793,
        791,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Share premium",
      "kind": "line",
      "values": [
        4002,
        4002,
        3983,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Retained earnings",
      "kind": "line",
      "values": [
        22334,
        18687,
        15616,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other components of equity",
      "kind": "line",
      "values": [
        -70,
        -3286,
        -2305,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Treasury shares",
      "kind": "line",
      "values": [
        -955,
        -590,
        -390,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total equity attributable to owners of the parent",
      "kind": "subtotal",
      "values": [
        26104,
        19606,
        17695,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Non-controlling interests",
      "kind": "line",
      "values": [
        80,
        90,
        35,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total equity",
      "kind": "total",
      "values": [
        26184,
        19696,
        17730,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Liabilities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Non-current liabilities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Non-current provisions",
      "kind": "line",
      "values": [
        3976,
        4630,
        5667,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Long-term financing liabilities",
      "kind": "line",
      "values": [
        9063,
        10355,
        10202,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Non-current contract liabilities",
      "kind": "line",
      "values": [
        26484,
        25572,
        23961,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Non-current other financial liabilities",
      "kind": "line",
      "values": [
        4809,
        7576,
        6715,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Non-current other liabilities",
      "kind": "line",
      "values": [
        477,
        463,
        450,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Deferred tax liabilities",
      "kind": "line",
      "values": [
        428,
        271,
        361,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Non-current deferred income",
      "kind": "line",
      "values": [
        7,
        27,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total non-current liabilities",
      "kind": "subtotal",
      "values": [
        45244,
        48894,
        47391,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Current liabilities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Current provisions",
      "kind": "line",
      "values": [
        4369,
        4307,
        4161,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Short-term financing liabilities",
      "kind": "line",
      "values": [
        5186,
        3924,
        3389,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Trade liabilities",
      "kind": "line",
      "values": [
        15878,
        13791,
        14323,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Current contract liabilities",
      "kind": "line",
      "values": [
        32112,
        30136,
        24537,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Current other financial liabilities",
      "kind": "line",
      "values": [
        1000,
        3050,
        2569,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Current other liabilities",
      "kind": "line",
      "values": [
        4223,
        4022,
        3507,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Current tax liabilities",
      "kind": "line",
      "values": [
        133,
        593,
        740,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Current deferred income",
      "kind": "line",
      "values": [
        528,
        725,
        450,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total current liabilities",
      "kind": "subtotal",
      "values": [
        63429,
        60548,
        53676,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Disposal group of liabilities classified as held for sale",
      "kind": "line",
      "values": [
        82,
        75,
        74,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total liabilities",
      "kind": "total",
      "values": [
        108755,
        109517,
        101141,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total equity and liabilities",
      "kind": "total",
      "values": [
        134939,
        129213,
        118871,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Equity attributable to equity owners of the parent",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Reserves",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Accumulated other comprehensive income",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Total equity attributable to equity owners of the parent",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Other Assets",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Prepaid expenses",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2265,
        2051
      ],
      "unit": "currency"
    },
    {
      "label": "Others",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        93,
        115
      ],
      "unit": "currency"
    },
    {
      "label": "Total non-current other assets",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2358,
        2166
      ],
      "unit": "currency"
    },
    {
      "label": "Value added tax claims",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1589,
        1450
      ],
      "unit": "currency"
    },
    {
      "label": "Total current other assets",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2576,
        2819
      ],
      "unit": "currency"
    },
    {
      "label": "Total",
      "kind": "total",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        4934,
        4985
      ],
      "unit": "currency"
    },
    {
      "label": "Other Liabilities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Customer advance payments",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        15714,
        14472
      ],
      "unit": "currency"
    },
    {
      "label": "Total non-current other liabilities",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        16279,
        14993
      ],
      "unit": "currency"
    },
    {
      "label": "Customer advance payments (1)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        24115,
        23612
      ],
      "unit": "currency"
    },
    {
      "label": "Tax liabilities (excluding income tax)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1047,
        885
      ],
      "unit": "currency"
    },
    {
      "label": "Total current other liabilities",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        27535,
        27037
      ],
      "unit": "currency"
    },
    {
      "label": "thereof other liabilities due within 1 year",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        26562,
        26313
      ],
      "unit": "currency"
    }
  ]
}

export const cashFlowStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015"
  ],
  "rows": [
    {
      "label": "Operating activities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Profit for the period attributable to equity owners of the parent (Net income)",
      "kind": "line",
      "values": [
        5221,
        4232,
        3789,
        4247,
        4213,
        null,
        null,
        3054,
        2361,
        995,
        2696
      ],
      "restatedIndices": [
        1,
        2,
        3,
        8,
        9
      ]
    },
    {
      "label": "Loss for the period attributable to non-controlling interests",
      "kind": "line",
      "values": [
        -261,
        -154,
        -176,
        -111,
        -39,
        -36,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Adjustments to reconcile profit for the period to cash provided by operating activities:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Interest income",
      "kind": "line",
      "values": [
        -710,
        -802,
        -728,
        -180,
        -88,
        -140,
        -228,
        -208,
        -189,
        -247,
        -183
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Interest expense",
      "kind": "line",
      "values": [
        770,
        900,
        753,
        412,
        334,
        411,
        339,
        440,
        517,
        522,
        551
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Interest received",
      "kind": "line",
      "values": [
        607,
        681,
        690,
        250,
        111,
        82,
        151,
        186,
        149,
        139,
        131
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Interest paid",
      "kind": "line",
      "values": [
        -651,
        -786,
        -606,
        -322,
        -330,
        -205,
        -187,
        -292,
        -501,
        -378,
        -388
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Income tax expense",
      "kind": "line",
      "values": [
        1390,
        1347,
        1156,
        939,
        853,
        39,
        2389,
        1274,
        1462,
        291,
        677
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Income tax paid",
      "kind": "line",
      "values": [
        -965,
        -947,
        -544,
        -790,
        -321,
        79,
        -1476,
        -897,
        -152,
        -559,
        -595
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Depreciation and amortisation",
      "kind": "line",
      "values": [
        3133,
        2853,
        2242,
        2716,
        2325,
        2831,
        2927,
        2444,
        2298,
        2294,
        2466
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        8,
        9
      ]
    },
    {
      "label": "Valuation adjustments",
      "kind": "line",
      "values": [
        -393,
        -640,
        -541,
        -569,
        -863,
        95,
        600,
        -1849,
        -1341,
        1132,
        487
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Results on disposals of non-current assets",
      "kind": "line",
      "values": [
        70,
        70,
        64,
        25,
        -116,
        9,
        -77,
        -261,
        -773,
        -1870,
        -234
      ],
      "restatedIndices": [
        2,
        3,
        4,
        5,
        7,
        8,
        9
      ]
    },
    {
      "label": "Results of investments accounted for under the equity method",
      "kind": "line",
      "values": [
        -305,
        -350,
        -267,
        -133,
        -40,
        -39,
        -299,
        -330,
        -311,
        -231,
        -1016
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Change in current and non-current provisions",
      "kind": "line",
      "values": [
        314,
        166,
        -114,
        -1016,
        -1934,
        1138,
        475,
        1952,
        1018,
        1321,
        -54
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Contribution to plan assets",
      "kind": "line",
      "values": [
        -272,
        -505,
        -668,
        -601,
        -533,
        -314,
        -1752,
        -2519,
        -458,
        -290,
        -217
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Change in other operating assets and liabilities",
      "kind": "line",
      "values": [
        1337,
        1337,
        1205,
        1421,
        1067,
        -8237,
        2216,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        2,
        3,
        4,
        5
      ]
    },
    {
      "label": "Inventories",
      "kind": "line",
      "values": [
        -3989,
        -3522,
        -1854,
        -3218,
        2405,
        152,
        117,
        -671,
        -2112,
        -3477,
        -4133
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Trade receivables",
      "kind": "line",
      "values": [
        -707,
        -105,
        258,
        -115,
        379,
        351,
        29,
        -881,
        -47,
        -1215,
        -1378
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Contract assets and liabilities",
      "kind": "line",
      "values": [
        3250,
        7135,
        2277,
        3300,
        -2326,
        848,
        1297,
        -684,
        2572,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ]
    },
    {
      "label": "Trade liabilities",
      "kind": "line",
      "values": [
        2791,
        -1182,
        1421,
        3309,
        194,
        194,
        -1625,
        2294,
        829,
        2398,
        894
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Other assets and liabilities",
      "kind": "line",
      "values": [
        -1245,
        -989,
        -897,
        -1855,
        415,
        -4065,
        2398,
        null,
        null,
        -837,
        -417
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "label": "Cash provided by operating activities",
      "kind": "total",
      "values": [
        7995,
        7402,
        6255,
        6288,
        4639,
        null,
        3753,
        2318,
        4444,
        4369,
        2891
      ],
      "restatedIndices": [
        1,
        2,
        3,
        7,
        8,
        9
      ]
    },
    {
      "label": "Investing activities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Purchases of intangible assets, property, plant and equipment, investment property",
      "kind": "line",
      "values": [
        -3964,
        -3669,
        -3051,
        -2464,
        -1928,
        -1759,
        -2340,
        -2285,
        -2558,
        -3060,
        -2924
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Proceeds from disposals of intangible assets, property, plant and equipment and investment property",
      "kind": "line",
      "values": [
        69,
        98,
        75,
        101,
        212,
        228,
        112,
        213,
        177,
        72,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8
      ]
    },
    {
      "label": "Acquisitions of subsidiaries and businesses (net of cash acquired) and joint ventures",
      "kind": "line",
      "values": [
        122,
        -246,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Proceeds from disposals of subsidiaries (net of cash)",
      "kind": "line",
      "values": [
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        377,
        731,
        127
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Payments for investments accounted for under the equity method, other investments and other long-term financial assets",
      "kind": "line",
      "values": [
        -879,
        -871,
        -960,
        -777,
        -577,
        -565,
        -952,
        -707,
        -913,
        -691,
        -258
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Proceeds from disposals of investments accounted for under the equity method, other investments and other long-term financial assets",
      "kind": "line",
      "values": [
        1083,
        530,
        509,
        459,
        396,
        408,
        358,
        597,
        532,
        182,
        1731
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Dividends paid by companies accounted for under the equity method",
      "kind": "line",
      "values": [
        387,
        196,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Disposals of non-current assets and disposal groups classified as assets held for sale and liabilities directly associated",
      "kind": "line",
      "values": [
        0,
        0,
        0,
        0,
        310,
        0,
        137,
        320,
        893,
        1527,
        127
      ],
      "restatedIndices": [
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Payments for investments in securities",
      "kind": "line",
      "values": [
        -5205,
        -4460,
        -2700,
        -1851,
        -3049,
        -337,
        -2861,
        -2010,
        -3767,
        -2280,
        -7151
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Proceeds from disposals of securities",
      "kind": "line",
      "values": [
        3678,
        1769,
        1914,
        1507,
        1863,
        6640,
        2464,
        1917,
        2534,
        2617,
        4790
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Cash (used for) investing activities",
      "kind": "total",
      "values": [
        -4682,
        -6653,
        -4128,
        -3113,
        -2719,
        null,
        -2864,
        -1635,
        -2530,
        -830,
        -3459
      ],
      "restatedIndices": [
        1,
        2,
        3,
        7,
        8,
        9
      ]
    },
    {
      "label": "Financing activities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Increase in financing liabilities",
      "kind": "line",
      "values": [
        244,
        851,
        247,
        171,
        0,
        7102,
        402,
        103,
        103,
        3297,
        1254
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Repayment of financing liabilities",
      "kind": "line",
      "values": [
        -858,
        -1283,
        -52,
        -1348,
        -2295,
        -445,
        -562,
        -2411,
        -419,
        -1725,
        -262
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Cash distribution to Airbus SE shareholders",
      "kind": "line",
      "values": [
        -2372,
        -2215,
        -1421,
        -1181,
        0,
        0,
        -1280,
        -1161,
        -1043,
        -1008,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8
      ]
    },
    {
      "label": "Dividends paid to non-controlling interests",
      "kind": "line",
      "values": [
        -2,
        -1,
        0,
        -1,
        0,
        null,
        0,
        0,
        -3,
        -4,
        -3
      ],
      "restatedIndices": [
        1,
        3,
        7,
        8,
        9
      ]
    },
    {
      "label": "Changes in capital and non-controlling interests",
      "kind": "line",
      "values": [
        82,
        354,
        146,
        145,
        138,
        89,
        194,
        117,
        83,
        60,
        195
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        7,
        8,
        9
      ]
    },
    {
      "label": "Change in treasury shares",
      "kind": "line",
      "values": [
        -565,
        -276,
        -334,
        -36,
        -22,
        -4,
        -31,
        -49,
        0,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ]
    },
    {
      "label": "Cash (used for) financing activities",
      "kind": "total",
      "values": [
        -3471,
        -2570,
        -1276,
        -2115,
        -2179,
        null,
        -958,
        -3222,
        null,
        -116,
        -25
      ],
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Effect of foreign exchange rate changes on cash and cash equivalents",
      "kind": "line",
      "values": [
        -712,
        358,
        -201,
        191,
        392,
        -414,
        -45,
        -54,
        -374,
        60,
        171
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Net (decrease) in cash and cash equivalents",
      "kind": "total",
      "values": [
        -870,
        -1463,
        null,
        null,
        null,
        null,
        -114,
        -2593,
        null,
        null,
        null
      ]
    },
    {
      "label": "Cash and cash equivalents at beginning of period",
      "kind": "line",
      "values": [
        15010,
        16473,
        15823,
        14572,
        14439,
        9314,
        9428,
        12021,
        10160,
        6677,
        7099
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Cash and cash equivalents at end of period",
      "kind": "total",
      "values": [
        14140,
        15010,
        16473,
        15823,
        14572,
        14439,
        9314,
        9428,
        12021,
        10160,
        6677
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "thereof presented as cash and cash equivalents",
      "kind": "line",
      "values": [
        14128,
        15003,
        16469,
        15823,
        null,
        null,
        9314,
        9413,
        12016,
        10143,
        6590
      ],
      "restatedIndices": [
        1,
        2,
        7,
        8,
        9
      ]
    },
    {
      "label": "thereof presented as part of disposal groups classified as held for sale",
      "kind": "line",
      "values": [
        12,
        7,
        4,
        0,
        null,
        null,
        0,
        15,
        5,
        17,
        87
      ],
      "restatedIndices": [
        1,
        2,
        7,
        8,
        9
      ]
    },
    {
      "label": "Acquisitions of subsidiaries, joint ventures and businesses (net of cash)",
      "kind": "line",
      "values": [
        null,
        -246,
        -65,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Dividends paid by companies valued under the equity method",
      "kind": "line",
      "values": [
        null,
        196,
        150,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Payments for liability for puttable instruments",
      "kind": "line",
      "values": [
        null,
        228,
        138,
        135,
        0,
        91,
        319,
        179,
        0,
        null,
        null
      ],
      "restatedIndices": [
        2,
        3,
        4,
        5,
        7
      ]
    },
    {
      "label": "Net (decrease) increase in cash and cash equivalents",
      "kind": "line",
      "values": [
        null,
        -1463,
        650,
        null,
        null,
        null,
        null,
        -2593,
        1861,
        null,
        null
      ]
    },
    {
      "label": "Acquisitions of subsidiaries, joint ventures, businesses and non‑controlling interests (net of cash)",
      "kind": "line",
      "values": [
        null,
        null,
        -65,
        -188,
        -25,
        -481,
        8,
        129,
        -23,
        -120,
        -13
      ],
      "restatedIndices": [
        3,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Dividends paid by companies valued at equity",
      "kind": "line",
      "values": [
        null,
        null,
        150,
        100,
        79,
        -8,
        210,
        191,
        218,
        192,
        34
      ],
      "restatedIndices": [
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Net increase in cash and cash equivalents",
      "kind": "line",
      "values": [
        null,
        null,
        650,
        1251,
        133,
        5125,
        null,
        null,
        1861,
        3483,
        null
      ],
      "restatedIndices": [
        3,
        4
      ]
    },
    {
      "label": "Profit (Loss) for the period attributable to equity owners of the parent (Net income)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        4213,
        -1133,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Cash provided by (used for) operating activities",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        4639,
        -5420,
        3753,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        5
      ]
    },
    {
      "label": "Cash provided by (used for) investing activities",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        -2719,
        4126,
        -2864,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        5
      ]
    },
    {
      "label": "Cash provided by (used for) financing activities",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        -2179,
        6833,
        -958,
        null,
        321,
        -116,
        null
      ],
      "restatedIndices": [
        5
      ]
    },
    {
      "label": "Loss for the period attributable to equity owners of the parent (Net income)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -1133,
        -1362,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "(Loss) Profit for the period attributable to non-controlling interests",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -36,
        37,
        -43,
        null,
        null,
        null
      ],
      "restatedIndices": [
        6
      ]
    },
    {
      "label": "Net increase (decrease) in cash and cash equivalents",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        5125,
        -114,
        null,
        null,
        3483,
        -422
      ]
    },
    {
      "label": "(Loss) Profit for the period attributable to equity owners of the parent (Net income)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -1362,
        3054,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Depreciation and amortization",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        2927,
        2444,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Other assets and liabilities and others",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        2398,
        -691,
        -881,
        -1089,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        7,
        8
      ]
    },
    {
      "label": "Profit (loss) for the period attributable to non-controlling interests",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -43,
        3,
        null,
        null
      ]
    },
    {
      "label": "Cash (used for) provided by financing activities",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -3222,
        321,
        null,
        null
      ]
    },
    {
      "label": "Profit for the period attributable to non-controlling interests",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        4,
        5,
        2
      ],
      "restatedIndices": [
        9
      ]
    },
    {
      "label": "Advance payments received",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1268,
        4628,
        3752
      ],
      "restatedIndices": [
        9
      ]
    },
    {
      "label": "Share buyback",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        -736,
        -264
      ],
      "restatedIndices": [
        9
      ]
    },
    {
      "label": "Customer financing assets",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -202,
        -193
      ]
    },
    {
      "label": "Customer financing liabilities",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -50,
        43
      ]
    },
    {
      "label": "Investments:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Proceeds from disposals of intangible assets, property, plant and equipment, investment property",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        72,
        78
      ]
    },
    {
      "label": "Cash distribution to Airbus Group SE shareholders",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -1008,
        -945
      ]
    }
  ]
}

export default { incomeStatement, balanceSheet, cashFlowStatement, sources, validation }
