// Generated by crawler/src/catalog.ts — do not edit by hand.
import type { Filing } from "@/lib/types"

export const filings: Record<string, Filing[]> = {
  "nvo": [
    {
      "year": 2026,
      "type": "Earnings Presentation",
      "title": "Q1-2026-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2026/Q1-2026-investor-presentation.pdf"
    },
    {
      "year": 2026,
      "type": "Earnings Presentation",
      "title": "novo-nordisk-r-and-d-investor-presentation-2026.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/ada/novo-nordisk-r-and-d-investor-presentation-2026.pdf"
    },
    {
      "year": 2025,
      "type": "Annual Report",
      "title": "novo-nordisk-annual-report-2025.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2026/novo-nordisk-annual-report-2025.pdf"
    },
    {
      "year": 2025,
      "type": "Annual Report",
      "title": "novo-nordisk-corporate-governance-report-2025.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2026/novo-nordisk-corporate-governance-report-2025.pdf"
    },
    {
      "year": 2025,
      "type": "Annual Report",
      "title": "novo-nordisk-remuneration-report-2025.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2026/novo-nordisk-remuneration-report-2025.pdf"
    },
    {
      "year": 2025,
      "type": "Annual Report",
      "title": "novo-nordisk-tax-report-2025.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2026/novo-nordisk-tax-report-2025.pdf"
    },
    {
      "year": 2025,
      "type": "Annual Report",
      "title": "novo-nordisk-form-20-f-2025.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2026/novo-nordisk-form-20-f-2025.pdf"
    },
    {
      "year": 2025,
      "type": "Annual Report",
      "title": "novo-nordisk-annual-report-2025.pdf",
      "url": "https://annualreport.novonordisk.com/2025/_assets/downloads/novo-nordisk-annual-report-2025.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2025,
      "type": "Earnings Presentation",
      "title": "Q4-2025-investor-presentation-4Feb.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2026/Q4-2025-investor-presentation-4Feb.pdf"
    },
    {
      "year": 2025,
      "type": "Earnings Presentation",
      "title": "Q3-investor-presentation-2025.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2025/Q3-investor-presentation-2025.pdf"
    },
    {
      "year": 2025,
      "type": "Earnings Presentation",
      "title": "Q2-2025-investor-presentation-updated.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2025/Q2-2025-investor-presentation-updated.pdf"
    },
    {
      "year": 2025,
      "type": "Earnings Presentation",
      "title": "Q1-2025-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2025/Q1-2025-investor-presentation.pdf"
    },
    {
      "year": 2024,
      "type": "Annual Report",
      "title": "novo-nordisk-annual-report-2024.pdf",
      "url": "https://annualreport.novonordisk.com/2024/_assets/downloads/novo-nordisk-annual-report-2024.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2024,
      "type": "Earnings Presentation",
      "title": "q4-2024-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2025/q4-2024-investor-presentation.pdf"
    },
    {
      "year": 2024,
      "type": "Earnings Presentation",
      "title": "q3-2024-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2024/q3-2024-investor-presentation.pdf"
    },
    {
      "year": 2024,
      "type": "Earnings Presentation",
      "title": "Q2-2024-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2024/Q2-2024-investor-presentation.pdf"
    },
    {
      "year": 2024,
      "type": "Earnings Presentation",
      "title": "q1-2024-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2024/q1-2024-investor-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Annual Report",
      "title": "novo-nordisk-annual-report-2023.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2024/novo-nordisk-annual-report-2023.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "q4-2023-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2023/q4-2023-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "Q3-2023-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2023/Q3-2023-investor-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "Q2-2023-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2023/Q2-2023-investor-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "Q1-2023-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2023/Q1-2023-investor-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "ada-investor-presentation-2023.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/ada/ada-investor-presentation-2023.pdf"
    },
    {
      "year": 2023,
      "type": "Press Release",
      "title": "v2-aha-investor-rresentation-2023.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2023/v2-aha-investor-rresentation-2023.pdf"
    },
    {
      "year": 2022,
      "type": "Annual Report",
      "title": "novo-nordisk-annual-report-2022.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2023/novo-nordisk-annual-report-2022.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2022,
      "type": "Earnings Presentation",
      "title": "Q4-2022-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2022/Q4-2022-investor-presentation.pdf"
    },
    {
      "year": 2022,
      "type": "Earnings Presentation",
      "title": "Q3-2022-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2022/Q3-2022-investor-presentation.pdf"
    },
    {
      "year": 2022,
      "type": "Earnings Presentation",
      "title": "Q2-2022-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2022/Q2-2022-investor-presentation.pdf"
    },
    {
      "year": 2022,
      "type": "Earnings Presentation",
      "title": "Q1-2022-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2022/Q1-2022-investor-presentation.pdf"
    },
    {
      "year": 2022,
      "type": "Earnings Presentation",
      "title": "novo-nordisk-ada-investor-presentation-2022.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/ada/novo-nordisk-ada-investor-presentation-2022.pdf"
    },
    {
      "year": 2021,
      "type": "Annual Report",
      "title": "novo-nordisk-annual-report-2021.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2022/novo-nordisk-annual-report-2021.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2021,
      "type": "Earnings Presentation",
      "title": "Q4-2021-full-investor-presentation.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/Q4-2021-full-investor-presentation.pdf"
    },
    {
      "year": 2021,
      "type": "Earnings Presentation",
      "title": "investor-presentation-Q3-2021.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/investor-presentation-Q3-2021.pdf"
    },
    {
      "year": 2021,
      "type": "Earnings Presentation",
      "title": "investor-presentation-Q2-2021.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/investor-presentation-Q2-2021.pdf"
    },
    {
      "year": 2021,
      "type": "Earnings Presentation",
      "title": "investor-presentation-Q1-2021.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/investor-presentation-Q1-2021.pdf"
    },
    {
      "year": 2021,
      "type": "Earnings Presentation",
      "title": "ada-investor-presentation-2021.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/ada-investor-presentation-2021.pdf"
    },
    {
      "year": 2021,
      "type": "Press Release",
      "title": "conference-call-supply-update-20Dec2021.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/conference-call-supply-update-20Dec2021.pdf"
    },
    {
      "year": 2021,
      "type": "Press Release",
      "title": "semaglutide-2-4-mg-approved-in-the-usa-2021.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/semaglutide-2-4-mg-approved-in-the-usa-2021.pdf"
    },
    {
      "year": 2021,
      "type": "Quarterly Statement",
      "title": "Q4-2021-company-announcement.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/Q4-2021-company-announcement.pdf"
    },
    {
      "year": 2021,
      "type": "Quarterly Statement",
      "title": "Q3-2021-company-announcement.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/Q3-2021-company-announcement.pdf"
    },
    {
      "year": 2021,
      "type": "Quarterly Statement",
      "title": "company-announcement-Q2-2021.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/financial-results/2021/company-announcement-Q2-2021.pdf"
    },
    {
      "year": 2021,
      "type": "Quarterly Statement",
      "title": "CA-Q1-2021.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/quarterly_financial_reports/2021/CA-Q1-2021.pdf"
    },
    {
      "year": 2020,
      "type": "Annual Report",
      "title": "Novo-Nordisk-Annual-Report-2020.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2021/Novo-Nordisk-Annual-Report-2020.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2019,
      "type": "Annual Report",
      "title": "Novo-Nordisk-Annual-Report-2019.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/annual-report/pdfs/2019/Novo-Nordisk-Annual-Report-2019.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2018,
      "type": "Annual Report",
      "title": "NN-AR17_UK_Online1.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2018/NN-AR17_UK_Online1.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2017,
      "type": "Annual Report",
      "title": "annual-report-2017.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/about-us/pdfs/corporate-governance/annual-general-meetings/agm2018/uk/annual-report-2017.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2017,
      "type": "Annual Report",
      "title": "20170207_Novo Nordisk Annual Report 2016.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2017/20170207_Novo%20Nordisk%20Annual%20Report%202016.pdf",
      "usedForExtraction": true
    },
    {
      "year": null,
      "type": "Other",
      "title": "novo-nordisk-r-and-d-investor-event.pdf",
      "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/pdfs/ada/novo-nordisk-r-and-d-investor-event.pdf"
    }
  ],
  "sap": [
    {
      "year": 2026,
      "type": "Earnings Presentation",
      "title": "sap-2026-q1-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2026/sap-2026-q1-presentation.pdf"
    },
    {
      "year": 2026,
      "type": "Earnings Presentation",
      "title": "sap-2026-q2-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2026/sap-2026-q2-presentation.pdf"
    },
    {
      "year": 2026,
      "type": "Earnings Presentation",
      "title": "sapphire-2026-financial-analyst-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2026/sapphire-2026-financial-analyst-presentation.pdf"
    },
    {
      "year": 2026,
      "type": "Half-Year Report",
      "title": "sap-2026-half-year-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2026/sap-2026-half-year-report.pdf"
    },
    {
      "year": 2026,
      "type": "Quarterly Statement",
      "title": "sap-2026-q1-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2026/sap-2026-q1-statement.pdf"
    },
    {
      "year": 2026,
      "type": "Quarterly Statement",
      "title": "sap-2026-q2-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2026/sap-2026-q2-statement.pdf"
    },
    {
      "year": 2025,
      "type": "Annual Report",
      "title": "sap-2025-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-annual-report-form-20f.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2025,
      "type": "Earnings Presentation",
      "title": "sap-2025-q1-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-q1-presentation.pdf"
    },
    {
      "year": 2025,
      "type": "Earnings Presentation",
      "title": "sap-2025-q2-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-q2-presentation.pdf"
    },
    {
      "year": 2025,
      "type": "Earnings Presentation",
      "title": "sap-2025-q3-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-q3-presentation.pdf"
    },
    {
      "year": 2025,
      "type": "Earnings Presentation",
      "title": "sap-2025-q4-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-q4-presentation.pdf"
    },
    {
      "year": 2025,
      "type": "Earnings Presentation",
      "title": "sapphire-2025-financial-analyst-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sapphire-2025-financial-analyst-presentation.pdf"
    },
    {
      "year": 2025,
      "type": "Half-Year Report",
      "title": "sap-2025-half-year-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-half-year-report.pdf"
    },
    {
      "year": 2025,
      "type": "Integrated Report",
      "title": "sap-2025-integrated-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-integrated-report.pdf"
    },
    {
      "year": 2025,
      "type": "Other",
      "title": "sap-2025-compensation-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-compensation-report.pdf"
    },
    {
      "year": 2025,
      "type": "Quarterly Statement",
      "title": "sap-2025-q1-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-q1-statement.pdf"
    },
    {
      "year": 2025,
      "type": "Quarterly Statement",
      "title": "sap-2025-q2-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-q2-statement.pdf"
    },
    {
      "year": 2025,
      "type": "Quarterly Statement",
      "title": "sap-2025-q3-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-q3-statement.pdf"
    },
    {
      "year": 2025,
      "type": "Quarterly Statement",
      "title": "sap-2025-q4-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-q4-statement.pdf"
    },
    {
      "year": 2024,
      "type": "Annual Report",
      "title": "sap-2024-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-annual-report-form-20f.pdf"
    },
    {
      "year": 2024,
      "type": "Earnings Presentation",
      "title": "sap-2024-q1-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-q1-presentation.pdf"
    },
    {
      "year": 2024,
      "type": "Earnings Presentation",
      "title": "sap-2024-q2-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-q2-presentation.pdf"
    },
    {
      "year": 2024,
      "type": "Earnings Presentation",
      "title": "sap-2024-q3-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-q3-presentation.pdf"
    },
    {
      "year": 2024,
      "type": "Earnings Presentation",
      "title": "sap-2024-q4-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-q4-presentation.pdf"
    },
    {
      "year": 2024,
      "type": "Earnings Presentation",
      "title": "sap-2024-financial-analyst-conference-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-financial-analyst-conference-presentation.pdf"
    },
    {
      "year": 2024,
      "type": "Half-Year Report",
      "title": "sap-2024-half-year-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-half-year-report.pdf"
    },
    {
      "year": 2024,
      "type": "Integrated Report",
      "title": "sap-2024-integrated-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-integrated-report.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2024,
      "type": "Other",
      "title": "sap-2024-compensation-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-compensation-report.pdf"
    },
    {
      "year": 2024,
      "type": "Quarterly Statement",
      "title": "sap-2024-q1-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-q1-statement.pdf"
    },
    {
      "year": 2024,
      "type": "Quarterly Statement",
      "title": "sap-2024-q2-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-q2-statement.pdf"
    },
    {
      "year": 2024,
      "type": "Quarterly Statement",
      "title": "sap-2024-q3-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-q3-statement.pdf"
    },
    {
      "year": 2024,
      "type": "Quarterly Statement",
      "title": "sap-2024-q4-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-q4-statement.pdf"
    },
    {
      "year": 2023,
      "type": "Annual Report",
      "title": "sap-2023-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-annual-report-form-20f.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "sap-2023-q1-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-q1-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "sap-2023-q2-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-q2-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "sap-2023-q3-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-q3-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "sap-2023-q4-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-q4-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Earnings Presentation",
      "title": "sap-2023-financial-analyst-conference-presentation.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-financial-analyst-conference-presentation.pdf"
    },
    {
      "year": 2023,
      "type": "Half-Year Report",
      "title": "sap-2023-half-year-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-half-year-report.pdf"
    },
    {
      "year": 2023,
      "type": "Integrated Report",
      "title": "sap-2023-integrated-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-integrated-report.pdf"
    },
    {
      "year": 2023,
      "type": "Other",
      "title": "sap-2023-compensation-report.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-compensation-report.pdf"
    },
    {
      "year": 2023,
      "type": "Quarterly Statement",
      "title": "sap-2023-q1-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-q1-statement.pdf"
    },
    {
      "year": 2023,
      "type": "Quarterly Statement",
      "title": "sap-2023-q2-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-q2-statement.pdf"
    },
    {
      "year": 2023,
      "type": "Quarterly Statement",
      "title": "sap-2023-q3-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-q3-statement.pdf"
    },
    {
      "year": 2023,
      "type": "Quarterly Statement",
      "title": "sap-2023-q4-statement.pdf",
      "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-q4-statement.pdf"
    },
    {
      "year": 2022,
      "type": "Annual Report",
      "title": "sap-2022-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2022/sap-2022-annual-report-form-20f.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2021,
      "type": "Annual Report",
      "title": "sap-2021-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2021/sap-2021-annual-report-form-20f.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2020,
      "type": "Annual Report",
      "title": "sap-2020-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2020/sap-2020-annual-report-form-20f.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2019,
      "type": "Annual Report",
      "title": "sap-2019-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2019/sap-2019-annual-report-form-20f.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2018,
      "type": "Annual Report",
      "title": "sap-2018-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2018/sap-2018-annual-report-form-20f.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2017,
      "type": "Annual Report",
      "title": "sap-2017-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2017/sap-2017-annual-report-form-20f.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2016,
      "type": "Annual Report",
      "title": "sap-2016-annual-report-form-20f.pdf",
      "url": "https://www.sap.com/docs/download/investors/2016/sap-2016-annual-report-form-20f.pdf",
      "usedForExtraction": true
    }
  ],
  "lvmh": [
    {
      "year": 2025,
      "type": "Financial Statements",
      "title": "aXjqHgIvOtkhB_8I_Financialdocuments-December31,2025.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/aXjqHgIvOtkhB_8I_Financialdocuments-December31%2C2025.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2025,
      "type": "Other",
      "title": "afy2RsBOoF08xujc_LVMH_Positive_Impact_2025.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/afy2RsBOoF08xujc_LVMH_Positive_Impact_2025.pdf"
    },
    {
      "year": 2025,
      "type": "Other",
      "title": "ac0pyZGXnQHGZK4S_LVMH_RA2025_GB_MEL1.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ac0pyZGXnQHGZK4S_LVMH_RA2025_GB_MEL1.pdf"
    },
    {
      "year": 2025,
      "type": "Other",
      "title": "aYB4Z90YXLCxVQWB_LVMH_SNAPSHOT_2025VA.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/aYB4Z90YXLCxVQWB_LVMH_SNAPSHOT_2025VA.pdf"
    },
    {
      "year": 2025,
      "type": "Registration Document",
      "title": "aczo-pGXnQHGZKQ5_UniversalRegistrationDocument2025.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/aczo-pGXnQHGZKQ5_UniversalRegistrationDocument2025.pdf"
    },
    {
      "year": 2024,
      "type": "Financial Statements",
      "title": "Z5kVBpbqstJ999KR_Financialdocuments-December31,2024.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/Z5kVBpbqstJ999KR_Financialdocuments-December31%2C2024.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2023,
      "type": "Financial Statements",
      "title": "ZmMq-pm069VX1j0w_financial-documents-lvmh-december-31-2023.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmMq-pm069VX1j0w_financial-documents-lvmh-december-31-2023.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2022,
      "type": "Financial Statements",
      "title": "ZmcHwJm069VX1mke_lvmh_document-financier-2022_uk-final.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmcHwJm069VX1mke_lvmh_document-financier-2022_uk-final.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2021,
      "type": "Financial Statements",
      "title": "Zmcg25m069VX1m3P_financial-documents-december-31-2021.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/Zmcg25m069VX1m3P_financial-documents-december-31-2021.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2020,
      "type": "Financial Statements",
      "title": "ZmgUWZm069VX1oC4_documents-financiers-2020_va_v2.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmgUWZm069VX1oC4_documents-financiers-2020_va_v2.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2019,
      "type": "Financial Statements",
      "title": "Zmg49Zm069VX1ofA_lvmh_documents-financiers_2019-va.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/Zmg49Zm069VX1ofA_lvmh_documents-financiers_2019-va.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2018,
      "type": "Financial Statements",
      "title": "ZmhMzZm069VX1ovO_2018-financial-documents.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmhMzZm069VX1ovO_2018-financial-documents.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2017,
      "type": "Financial Statements",
      "title": "Zmh3UJm069VX1pT-_2017-financial-documents.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/Zmh3UJm069VX1pT-_2017-financial-documents.pdf",
      "usedForExtraction": true
    },
    {
      "year": 2016,
      "type": "Financial Statements",
      "title": "ZmmTjpm069VX1rMJ_lvmh_financial-documents-_va.pdf",
      "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmmTjpm069VX1rMJ_lvmh_financial-documents-_va.pdf",
      "usedForExtraction": true
    }
  ]
}
