// Generated by crawler/src/extract.ts — do not edit by hand.
import type { StatementData } from "@/lib/types"

// The report PDFs these numbers were extracted from.
export const sources = [
  {
    "year": 2025,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/aXjqHgIvOtkhB_8I_Financialdocuments-December31%2C2025.pdf"
  },
  {
    "year": 2024,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/Z5kVBpbqstJ999KR_Financialdocuments-December31%2C2024.pdf"
  },
  {
    "year": 2023,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmMq-pm069VX1j0w_financial-documents-lvmh-december-31-2023.pdf"
  },
  {
    "year": 2022,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmcHwJm069VX1mke_lvmh_document-financier-2022_uk-final.pdf"
  },
  {
    "year": 2021,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/Zmcg25m069VX1m3P_financial-documents-december-31-2021.pdf"
  },
  {
    "year": 2020,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmgUWZm069VX1oC4_documents-financiers-2020_va_v2.pdf"
  },
  {
    "year": 2019,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/Zmg49Zm069VX1ofA_lvmh_documents-financiers_2019-va.pdf"
  },
  {
    "year": 2018,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmhMzZm069VX1ovO_2018-financial-documents.pdf"
  },
  {
    "year": 2017,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/Zmh3UJm069VX1pT-_2017-financial-documents.pdf"
  },
  {
    "year": 2016,
    "url": "https://lvmh-com.cdn.prismic.io/lvmh-com/ZmmTjpm069VX1rMJ_lvmh_financial-documents-_va.pdf"
  }
]

// Cross-statement validation result (accounting identities) at extraction time.
export const validation = {
  "status": "warning",
  "issues": [
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2025",
      "expected": 8794,
      "actual": 8359,
      "diff": -435
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2024",
      "expected": 9631,
      "actual": 9269,
      "diff": -362
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2023",
      "expected": 7774,
      "actual": 7520,
      "diff": -254
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2022",
      "expected": 7300,
      "actual": 7100,
      "diff": -200
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2021",
      "expected": 8021,
      "actual": 7817,
      "diff": -204
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2020",
      "expected": 19963,
      "actual": 19806,
      "diff": -157
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2019",
      "expected": 5673,
      "actual": 5497,
      "diff": -176
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2018",
      "expected": 4610,
      "actual": 4413,
      "diff": -197
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2017",
      "expected": 3738,
      "actual": 3618,
      "diff": -120
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2016",
      "expected": 3544,
      "actual": 3337,
      "diff": -207
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2015",
      "expected": 3594,
      "actual": 3390,
      "diff": -204
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2014",
      "expected": 4091,
      "actual": 3783,
      "diff": -308
    }
  ]
} as const

export const incomeStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014"
  ],
  "rows": [
    {
      "label": "Revenue",
      "kind": "line",
      "values": [
        80807,
        84683,
        86153,
        79184,
        64215,
        44651,
        53670,
        46826,
        42636,
        37600,
        35664,
        30638
      ],
      "unit": "currency"
    },
    {
      "label": "Cost of sales",
      "kind": "line",
      "values": [
        -27279,
        -27918,
        -26876,
        -24988,
        -20355,
        -15871,
        -18123,
        -15625,
        -14783,
        -13039,
        -12553,
        -10801
      ],
      "unit": "currency"
    },
    {
      "label": "Gross margin",
      "kind": "line",
      "values": [
        53528,
        56765,
        59277,
        54196,
        43860,
        28780,
        35547,
        31201,
        27853,
        24561,
        23111,
        19837
      ],
      "unit": "currency"
    },
    {
      "label": "Marketing and selling expenses",
      "kind": "line",
      "values": [
        -29914,
        -31002,
        -30768,
        -28151,
        -22308,
        -16792,
        -20207,
        -17755,
        -16395,
        -14607,
        -13830,
        -11744
      ],
      "unit": "currency"
    },
    {
      "label": "General and administrative expenses",
      "kind": "line",
      "values": [
        -5934,
        -6220,
        -5714,
        -5027,
        -4414,
        -3641,
        -3864,
        -3466,
        -3162,
        -2931,
        -2663,
        -2373
      ],
      "unit": "currency"
    },
    {
      "label": "Income/(Loss) from joint ventures and associates",
      "kind": "line",
      "values": [
        75,
        28,
        7,
        37,
        13,
        -42,
        28,
        23,
        -3,
        3,
        -13,
        -5
      ],
      "unit": "currency"
    },
    {
      "label": "Profit from recurring operations",
      "kind": "line",
      "values": [
        17755,
        19571,
        22802,
        21055,
        17151,
        8305,
        11504,
        10003,
        8293,
        7026,
        6605,
        5715
      ],
      "unit": "currency"
    },
    {
      "label": "Other operating income and expenses",
      "kind": "line",
      "values": [
        -656,
        -664,
        -242,
        -54,
        4,
        -333,
        -231,
        -126,
        -180,
        -122,
        -221,
        -284
      ],
      "unit": "currency"
    },
    {
      "label": "Operating profit",
      "kind": "line",
      "values": [
        17099,
        18907,
        22560,
        21001,
        17155,
        7972,
        11273,
        9877,
        8113,
        6904,
        6384,
        5431
      ],
      "unit": "currency"
    },
    {
      "label": "Cost of net financial debt",
      "kind": "line",
      "values": [
        -348,
        -442,
        -367,
        -17,
        -41,
        -35,
        -107,
        -117,
        -137,
        -133,
        -78,
        -115
      ],
      "unit": "currency",
      "restatedIndices": [
        4,
        5,
        8,
        9
      ]
    },
    {
      "label": "Interest on lease liabilities",
      "kind": "line",
      "values": [
        -553,
        -510,
        -393,
        -254,
        -242,
        -281,
        -290,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Other financial income and expenses",
      "kind": "line",
      "values": [
        500,
        160,
        -175,
        -617,
        254,
        -292,
        -162,
        -271,
        78,
        -185,
        -336,
        3062
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Net financial income/(expense)",
      "kind": "line",
      "values": [
        -401,
        -792,
        -935,
        -888,
        53,
        -608,
        -559,
        -388,
        -59,
        -318,
        -414,
        2947
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Income taxes",
      "kind": "line",
      "values": [
        -5476,
        -5157,
        -5673,
        -5362,
        -4510,
        -2409,
        -2932,
        -2499,
        -2214,
        -2133,
        -1969,
        -2273
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Net profit before minority interests",
      "kind": "line",
      "values": [
        11222,
        12958,
        15952,
        14751,
        12698,
        4955,
        7782,
        6990,
        5840,
        4453,
        4001,
        6105
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Minority interests",
      "kind": "line",
      "values": [
        -344,
        -408,
        -778,
        -667,
        -662,
        -253,
        -611,
        -636,
        -475,
        -387,
        -428,
        -457
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Net profit, Group share",
      "kind": "line",
      "values": [
        10878,
        12550,
        15174,
        14084,
        12036,
        4702,
        7171,
        6354,
        5365,
        4066,
        3573,
        5648
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Basic Group share of net earnings per share (EUR)",
      "kind": "line",
      "values": [
        21.86,
        25.13,
        30.34,
        28.05,
        23.9,
        9.33,
        14.25,
        12.64,
        10.68,
        8.08,
        7.11,
        11.27
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Number of shares on which the calculation is based",
      "kind": "line",
      "values": [
        497650238,
        499412515,
        500056586,
        502120694,
        503627708,
        503679272,
        503218851,
        502825461,
        502412694,
        502911125,
        502395491,
        501309369
      ],
      "unit": "shares"
    },
    {
      "label": "Diluted Group share of net earnings per share (EUR)",
      "kind": "line",
      "values": [
        21.85,
        25.12,
        30.33,
        28.03,
        23.89,
        9.32,
        14.23,
        12.61,
        10.64,
        8.06,
        7.08,
        11.21
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Number of shares on which the calculation is based",
      "kind": "line",
      "values": [
        497976118,
        499681046,
        500304316,
        502480100,
        503895592,
        504210133,
        503839542,
        503918140,
        504010291,
        504640459,
        504894946,
        503861733
      ],
      "unit": "shares"
    }
  ]
}

export const balanceSheet: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014"
  ],
  "rows": [
    {
      "label": "Assets",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Brands and other intangible assets",
      "kind": "line",
      "values": [
        23129,
        26280,
        25589,
        25432,
        24551,
        17012,
        17212,
        17254,
        16957,
        13335,
        13572,
        13031
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Goodwill",
      "kind": "line",
      "values": [
        18315,
        20307,
        24022,
        24782,
        25904,
        16042,
        16034,
        13727,
        13837,
        10401,
        10122,
        8810
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Property, plant and equipment",
      "kind": "line",
      "values": [
        29728,
        29886,
        27331,
        23055,
        20193,
        18224,
        18533,
        15112,
        13862,
        12139,
        11157,
        10387
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Right-of-use assets",
      "kind": "line",
      "values": [
        14860,
        16620,
        15679,
        14615,
        13705,
        12521,
        12409,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Investments in joint ventures and associates",
      "kind": "line",
      "values": [
        1214,
        1343,
        991,
        1066,
        1084,
        990,
        1074,
        638,
        639,
        770,
        729,
        519
      ],
      "unit": "currency"
    },
    {
      "label": "Non-current available for sale financial assets",
      "kind": "line",
      "values": [
        1891,
        1632,
        1363,
        1109,
        1363,
        739,
        915,
        1100,
        789,
        744,
        574,
        580
      ],
      "unit": "currency"
    },
    {
      "label": "Other non-current assets",
      "kind": "line",
      "values": [
        983,
        1106,
        1017,
        1186,
        1054,
        845,
        1546,
        986,
        869,
        777,
        552,
        489
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Deferred tax",
      "kind": "line",
      "values": [
        3738,
        4545,
        3992,
        3661,
        3156,
        2325,
        2274,
        1932,
        1741,
        2053,
        1945,
        1436
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Non-current assets",
      "kind": "subtotal",
      "values": [
        93858,
        101719,
        99984,
        94906,
        91010,
        68698,
        69997,
        50749,
        48694,
        40219,
        38651,
        35252
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Inventories and work in progress",
      "kind": "line",
      "values": [
        22659,
        23669,
        22952,
        20319,
        16549,
        13016,
        13717,
        12485,
        10888,
        10546,
        10096,
        9475
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Trade accounts receivable",
      "kind": "line",
      "values": [
        4332,
        4730,
        4728,
        4258,
        3787,
        2756,
        3450,
        3222,
        2736,
        2685,
        2521,
        2274
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Income taxes",
      "kind": "line",
      "values": [
        758,
        986,
        533,
        375,
        338,
        392,
        406,
        366,
        780,
        280,
        384,
        354
      ],
      "unit": "currency"
    },
    {
      "label": "Other current assets",
      "kind": "line",
      "values": [
        8840,
        8455,
        7723,
        7488,
        5606,
        3846,
        3264,
        2868,
        2919,
        2342,
        2355,
        1916
      ],
      "unit": "currency",
      "restatedIndices": [
        9
      ]
    },
    {
      "label": "Assets held for sale",
      "kind": "line",
      "values": [
        2796,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Cash and cash equivalents",
      "kind": "line",
      "values": [
        8794,
        9631,
        7774,
        7300,
        8021,
        19963,
        5673,
        4610,
        3738,
        3544,
        3594,
        4091
      ],
      "unit": "currency"
    },
    {
      "label": "Current assets",
      "kind": "subtotal",
      "values": [
        48179,
        47471,
        43710,
        39740,
        34301,
        39973,
        26510,
        23551,
        21061,
        19397,
        18950,
        18110
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Total assets",
      "kind": "total",
      "values": [
        142037,
        149190,
        143694,
        134646,
        125311,
        108671,
        96507,
        74300,
        69755,
        59616,
        57601,
        53362
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Liabilities and equity",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Equity, Group share",
      "kind": "line",
      "values": [
        67472,
        67517,
        61017,
        55111,
        47119,
        37412,
        36586,
        32293,
        28969,
        26388,
        24339,
        21763
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Minority interests",
      "kind": "line",
      "values": [
        1477,
        1770,
        1684,
        1493,
        1790,
        1417,
        1779,
        1664,
        1408,
        1510,
        1460,
        1240
      ],
      "unit": "currency"
    },
    {
      "label": "Equity",
      "kind": "subtotal",
      "values": [
        68949,
        69287,
        62701,
        56604,
        48909,
        38829,
        38365,
        33957,
        30377,
        27898,
        25799,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Long-term borrowings",
      "kind": "line",
      "values": [
        12418,
        12091,
        11227,
        10380,
        12165,
        14065,
        5101,
        6005,
        7046,
        3932,
        4511,
        5054
      ],
      "unit": "currency"
    },
    {
      "label": "Non-current lease liabilities",
      "kind": "line",
      "values": [
        13384,
        14860,
        13810,
        12776,
        11887,
        10665,
        10373,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Non-current provisions and other liabilities",
      "kind": "line",
      "values": [
        3546,
        3856,
        3880,
        3902,
        3980,
        3322,
        3812,
        3188,
        3177,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Deferred tax",
      "kind": "line",
      "values": [
        6993,
        7344,
        7012,
        6952,
        6704,
        5481,
        5498,
        5036,
        4989,
        4137,
        4685,
        4392
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Purchase commitments for minority interests’ shares",
      "kind": "line",
      "values": [
        6331,
        8056,
        11919,
        12489,
        13677,
        10991,
        10735,
        9281,
        9177,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Non-current liabilities",
      "kind": "subtotal",
      "values": [
        42672,
        46207,
        47848,
        46498,
        48413,
        44524,
        35519,
        23510,
        24389,
        18908,
        19103,
        18184
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Short-term borrowings",
      "kind": "line",
      "values": [
        7925,
        10851,
        10680,
        9359,
        8075,
        10638,
        7610,
        5027,
        4530,
        3447,
        3769,
        4189
      ],
      "unit": "currency"
    },
    {
      "label": "Current lease liabilities",
      "kind": "line",
      "values": [
        2634,
        2972,
        2728,
        2632,
        2387,
        2163,
        2172,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Trade accounts payable",
      "kind": "line",
      "values": [
        8223,
        8630,
        9049,
        8788,
        7086,
        5098,
        5814,
        5314,
        4539,
        4184,
        3960,
        3606
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Income taxes",
      "kind": "line",
      "values": [
        828,
        1231,
        1148,
        1211,
        1267,
        721,
        722,
        538,
        763,
        428,
        640,
        549
      ],
      "unit": "currency"
    },
    {
      "label": "Current provisions and other liabilities",
      "kind": "line",
      "values": [
        9190,
        10012,
        9540,
        9553,
        9174,
        6698,
        6305,
        5954,
        5157,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Liabilities held for sale",
      "kind": "line",
      "values": [
        1616,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Current liabilities",
      "kind": "subtotal",
      "values": [
        30416,
        33696,
        33145,
        31543,
        27989,
        25318,
        22623,
        16833,
        14989,
        12810,
        12699,
        12175
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Total liabilities and equity",
      "kind": "total",
      "values": [
        142037,
        149190,
        143694,
        134646,
        125311,
        108671,
        96507,
        74300,
        69755,
        59616,
        57601,
        53362
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Share capital",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        152,
        152,
        152,
        152,
        152
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Share premium account",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2298,
        2614,
        2601,
        2579,
        2655
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Treasury shares and LVMH share-settled derivatives",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -421,
        -530,
        -520,
        -240,
        -374
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Cumulative translation adjustment",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        573,
        354,
        1165,
        1137,
        492
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ],
      "historical": true
    },
    {
      "label": "Revaluation reserves",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        875,
        1111,
        799,
        949,
        1019
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Other reserves",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        22462,
        19903,
        18125,
        16189,
        12171
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Net profit, Group share",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        6354,
        5365,
        4066,
        3573,
        5648
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Non-current provisions",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2430,
        2484,
        2342,
        1950,
        2291
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ],
      "historical": true
    },
    {
      "label": "Other non-current liabilities",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        10039,
        9870,
        8497,
        7957,
        6447
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Current provisions",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        369,
        404,
        352,
        421,
        332
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Other current liabilities",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        5585,
        4753,
        4399,
        3909,
        3499
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ],
      "historical": true
    },
    {
      "label": "Total equity",
      "kind": "total",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        27903,
        25799,
        23003
      ],
      "unit": "currency",
      "historical": true
    }
  ]
}

export const cashFlowStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014"
  ],
  "rows": [
    {
      "label": "I. OPERATING ACTIVITIES",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Operating profit",
      "kind": "line",
      "values": [
        17099,
        18907,
        22560,
        21001,
        17155,
        7972,
        11273,
        9877,
        8113,
        6904,
        6384,
        5431
      ]
    },
    {
      "label": "(Income)/Loss and dividends received from joint ventures and associates",
      "kind": "line",
      "values": [
        13,
        29,
        42,
        26,
        41,
        64,
        -10,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Net increase in depreciation, amortization and provisions",
      "kind": "line",
      "values": [
        4858,
        4568,
        4146,
        3219,
        3139,
        3478,
        2700,
        2302,
        2376,
        2143,
        2081,
        1895
      ],
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Depreciation of right-of-use assets",
      "kind": "line",
      "values": [
        3143,
        3228,
        3031,
        3007,
        2691,
        2572,
        2408,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Other adjustments and computed expenses",
      "kind": "line",
      "values": [
        -172,
        488,
        -259,
        -483,
        -405,
        -89,
        -266,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Cash from operations before changes in working capital",
      "kind": "line",
      "values": [
        24941,
        27220,
        29520,
        26770,
        22621,
        13997,
        16105,
        11965,
        10405,
        8733,
        7945,
        7080
      ],
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Cost of net financial debt: interest paid",
      "kind": "line",
      "values": [
        -290,
        -357,
        -457,
        -74,
        71,
        -58,
        -124,
        -113,
        -129,
        -122,
        -75,
        -116
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Lease liabilities: interest paid",
      "kind": "line",
      "values": [
        -545,
        -483,
        -356,
        -240,
        -231,
        -290,
        -239,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Tax paid",
      "kind": "line",
      "values": [
        -4656,
        -5531,
        -5730,
        -5604,
        -4239,
        -2385,
        -2940,
        -2275,
        -2790,
        -1923,
        -1807,
        null
      ]
    },
    {
      "label": "Change in working capital",
      "kind": "line",
      "values": [
        -576,
        -1925,
        -4577,
        -3019,
        426,
        -367,
        -1154,
        -1087,
        -514,
        -512,
        -429,
        -718
      ]
    },
    {
      "label": "Net cash from/(used in) operating activities",
      "kind": "line",
      "values": [
        18874,
        18924,
        18400,
        17833,
        18648,
        10897,
        11648,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "II. INVESTING ACTIVITIES",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Operating investments",
      "kind": "line",
      "values": [
        -4567,
        -5531,
        -7478,
        -4969,
        -2664,
        -2478,
        -3294,
        -3038,
        -2276,
        -2265,
        -1955,
        -1775
      ]
    },
    {
      "label": "Purchase and proceeds from sale of consolidated investments",
      "kind": "line",
      "values": [
        149,
        -438,
        -721,
        -809,
        -13226,
        -536,
        -2478,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Dividends received",
      "kind": "line",
      "values": [
        21,
        9,
        5,
        7,
        10,
        12,
        8,
        18,
        13,
        55,
        4,
        69
      ],
      "restatedIndices": [
        1,
        2,
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Tax paid related to non-current available for sale financial assets and consolidated investments",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -1,
        null,
        -461,
        -461,
        -265,
        null
      ]
    },
    {
      "label": "Purchase and proceeds from sale of non-current available for sale financial assets",
      "kind": "line",
      "values": [
        -243,
        -579,
        -116,
        -149,
        -99,
        63,
        -104,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Net cash from/(used in) investing activities",
      "kind": "line",
      "values": [
        -4640,
        -6539,
        -8310,
        -5920,
        -15979,
        -2939,
        -5869,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "III. FINANCING ACTIVITIES",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Interim and final dividends paid",
      "kind": "line",
      "values": [
        -7123,
        -7322,
        -7159,
        -6774,
        -4161,
        -2799,
        -3678,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Purchase and proceeds from sale of minority interests",
      "kind": "line",
      "values": [
        -1091,
        -173,
        -17,
        -351,
        -435,
        -67,
        -21,
        -236,
        -153,
        -95,
        -4,
        10
      ]
    },
    {
      "label": "Other equity-related transactions",
      "kind": "line",
      "values": [
        -1634,
        -224,
        -1569,
        -1604,
        -552,
        27,
        54,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Proceeds from borrowings",
      "kind": "line",
      "values": [
        2095,
        3595,
        5990,
        3774,
        251,
        17499,
        2837,
        1529,
        5931,
        913,
        1008,
        2407
      ],
      "restatedIndices": [
        4,
        5,
        8
      ]
    },
    {
      "label": "Repayment of borrowings",
      "kind": "line",
      "values": [
        -4228,
        -3676,
        -3968,
        -3891,
        -6413,
        -5024,
        -1810,
        -2174,
        -1760,
        -2181,
        -2443,
        -2100
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Repayment of lease liabilities",
      "kind": "line",
      "values": [
        -2974,
        -2915,
        -2818,
        -2751,
        -2453,
        -2302,
        -2187,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Purchase and proceeds from sale of current available for sale financial assets",
      "kind": "line",
      "values": [
        59,
        -1,
        144,
        -1088,
        -1393,
        69,
        71,
        -147,
        92,
        -104,
        -3,
        -106
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Net cash from/(used in) financing activities",
      "kind": "line",
      "values": [
        -14896,
        -10716,
        -9397,
        -12685,
        -15156,
        7403,
        -4734,
        -792,
        4263,
        -1372,
        -1438,
        201
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "IV. EFFECT OF EXCHANGE RATE CHANGES",
      "kind": "line",
      "values": [
        -248,
        80,
        -273,
        55,
        498,
        -1052,
        39,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "NET INCREASE/(DECREASE) IN CASH AND CASH EQUIVALENTS (I+II+III+IV)",
      "kind": "total",
      "values": [
        -910,
        1749,
        420,
        -717,
        -11989,
        14309,
        1084,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "CASH AND CASH EQUIVALENTS AT BEGINNING OF PERIOD",
      "kind": "line",
      "values": [
        9269,
        7520,
        7100,
        7817,
        19806,
        5497,
        4413,
        3618,
        3337,
        3390,
        3783,
        2916
      ]
    },
    {
      "label": "CASH AND CASH EQUIVALENTS AT END OF PERIOD",
      "kind": "line",
      "values": [
        8359,
        9269,
        7520,
        7100,
        7817,
        19806,
        5497,
        4413,
        3618,
        3337,
        3390,
        3783
      ]
    },
    {
      "label": "TOTAL TAX PAID",
      "kind": "line",
      "values": [
        -4901,
        -5790,
        -6106,
        -5933,
        -4464,
        -2501,
        -3070,
        -2314,
        -2402,
        -2529,
        -2376,
        null
      ]
    },
    {
      "label": "Alternative performance measure",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Net cash from operating activities",
      "kind": "line",
      "values": [
        18874,
        18924,
        18400,
        17833,
        18648,
        10897,
        11648,
        8490,
        6972,
        6176,
        5634,
        4607
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Operating investments",
      "kind": "line",
      "values": [
        -4567,
        -5531,
        -7478,
        -4969,
        -2664,
        -2478,
        -3294,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Repayment of lease liabilities",
      "kind": "line",
      "values": [
        -2974,
        -2915,
        -2818,
        -2751,
        -2453,
        -2302,
        -2187,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Operating free cash flow (a)",
      "kind": "total",
      "values": [
        11333,
        10478,
        8104,
        10113,
        13531,
        6117,
        6167,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "I. OPERATING ACTIVITIES AND OPERATING INVESTMENTS",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Income/(loss) and dividends from joint ventures and associates",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        5,
        25,
        18,
        27,
        26
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Other computed expenses",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -141,
        -43,
        -177,
        -456,
        -188
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Other adjustments",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -78,
        -66,
        -155,
        -91,
        -84
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Net cash from operating activities before changes in working capital",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        9577,
        7486,
        6688,
        6063,
        5325
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Net cash from operating activities and operating investments (free cash flow)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        5452,
        4696,
        3911,
        3679,
        2832
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "II. FINANCIAL INVESTMENTS",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Purchase of non-current available for sale financial assets",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -445,
        -125,
        -28,
        -78,
        -57
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Proceeds from sale of non-current available for sale financial assets",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        45,
        87,
        91,
        68,
        160
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Impact of purchase and sale of consolidated investments",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -17,
        -6306,
        310,
        -240,
        -167
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Net cash from (used in) financial investments",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -401,
        -6331,
        -33,
        -511,
        -232
      ],
      "unit": "currency",
      "restatedIndices": [
        9
      ],
      "historical": true
    },
    {
      "label": "III. TRANSACTIONS RELATING TO EQUITY",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Capital increases of LVMH SE",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        49,
        53,
        64,
        35,
        59
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Capital increases of subsidiaries subscribed by minority interests",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        41,
        44,
        41,
        81,
        3
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Acquisition and disposals of treasury shares and LVMH share-settled derivatives",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -295,
        -67,
        -352,
        1,
        1
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Interim and final dividends paid by LVMH SE",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -2715,
        -2110,
        -1859,
        -1671,
        -1619
      ],
      "unit": "currency",
      "restatedIndices": [
        9
      ],
      "historical": true
    },
    {
      "label": "Tax paid related to interim and final dividends paid",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -36,
        388,
        -145,
        -304,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Interim and final dividends paid to minority interests in consolidated subsidiaries",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -339,
        -260,
        -267,
        -228,
        -336
      ],
      "unit": "currency",
      "restatedIndices": [
        8
      ],
      "historical": true
    },
    {
      "label": "Net cash from (used in) transactions relating to equity",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -3531,
        -2105,
        -2613,
        -2090,
        -1961
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Change in cash before financing activities",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1520,
        -3740,
        1265,
        1078,
        639
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "IV. FINANCING ACTIVITIES",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "V. EFFECT OF EXCHANGE RATE CHANGES",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -47,
        -33,
        27
      ]
    },
    {
      "label": "Effect of exchange rate changes",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        67,
        -242,
        54,
        -33,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "NET INCREASE (DECREASE) IN CASH AND CASH EQUIVALENTS (I+II+III+IV+V)",
      "kind": "total",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        795,
        281,
        -53,
        -393,
        867
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Income taxes paid",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -1923,
        -1807,
        -1639
      ],
      "historical": true
    },
    {
      "label": "Income taxes paid related to financial investments and consolidated investments",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -461,
        -265,
        -237
      ],
      "historical": true
    },
    {
      "label": "Income taxes paid related to interim and final dividends paid",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -145,
        -304,
        -79
      ],
      "historical": true
    },
    {
      "label": "TOTAL INCOME TAXES PAID",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -2529,
        -2376,
        -1955
      ],
      "historical": true
    }
  ]
}

export default { incomeStatement, balanceSheet, cashFlowStatement, sources, validation }
