// Generated by crawler/src/extract.ts — do not edit by hand.
import type { StatementData } from "@/lib/types"

// The report PDFs these numbers were extracted from.
export const sources = [
  {
    "year": 2025,
    "url": "https://annualreport.novonordisk.com/2025/_assets/downloads/novo-nordisk-annual-report-2025.pdf?h=9UdfHgQ-"
  },
  {
    "year": 2024,
    "url": "https://annualreport.novonordisk.com/2024/_assets/downloads/novo-nordisk-annual-report-2024.pdf?h=65BP4O4N"
  }
]

// Cross-statement validation result (accounting identities) at extraction time.
export const validation = {
  "status": "pass",
  "issues": []
} as const

export const incomeStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022"
  ],
  "rows": [
    {
      "label": "Income statement",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Net sales",
      "kind": "line",
      "values": [
        309064,
        290403,
        232261,
        176954
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Cost of goods sold",
      "kind": "line",
      "values": [
        -58788,
        -44522,
        -35765,
        -28448
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Gross profit",
      "kind": "line",
      "values": [
        250276,
        245881,
        196496,
        148506
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Sales and distribution costs",
      "kind": "line",
      "values": [
        -64310,
        -62101,
        -56743,
        -46217
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Research and development costs",
      "kind": "line",
      "values": [
        -52039,
        -48062,
        -32443,
        -24047
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Administrative costs",
      "kind": "line",
      "values": [
        -5969,
        -5276,
        -4855,
        -4467
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Other operating income and expenses",
      "kind": "line",
      "values": [
        -300,
        -2103,
        119,
        1034
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Operating profit",
      "kind": "subtotal",
      "values": [
        127658,
        128339,
        102574,
        74809
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Financial income",
      "kind": "line",
      "values": [
        9660,
        6198,
        2945,
        239
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Financial expenses",
      "kind": "line",
      "values": [
        -6778,
        -7346,
        -845,
        -5986
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Profit before income taxes",
      "kind": "subtotal",
      "values": [
        130540,
        127191,
        104674,
        69062
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Income taxes",
      "kind": "line",
      "values": [
        -28106,
        -26203,
        -20991,
        -13537
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Net profit",
      "kind": "subtotal",
      "values": [
        102434,
        100988,
        83683,
        55525
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Earnings per share",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Basic earnings per share (DKK)",
      "kind": "line",
      "values": [
        23.06,
        22.67,
        18.67,
        12.26
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Diluted earnings per share (DKK)",
      "kind": "line",
      "values": [
        23.03,
        22.63,
        18.62,
        12.22
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Statement of comprehensive income",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Other comprehensive income:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Exchange rate adjustments of investments in subsidiaries",
      "kind": "line",
      "values": [
        -7759,
        3096,
        -1404,
        2289
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Cash flow hedges:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Realisation of previously deferred (gains)/losses",
      "kind": "line",
      "values": [
        5763,
        -1612,
        -1026,
        1740
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Deferred gains/(losses) related to acquisition of businesses",
      "kind": "line",
      "values": [
        null,
        1154,
        0,
        0
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Deferred gains/(losses) on hedges open at year-end",
      "kind": "line",
      "values": [
        4339,
        -5763,
        1612,
        1026
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Tax and other items",
      "kind": "line",
      "values": [
        -2632,
        1343,
        -355,
        -892
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Items that will be reclassified subsequently to the income statement",
      "kind": "subtotal",
      "values": [
        -289,
        -1782,
        -1173,
        4163
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Remeasurements of retirement benefit obligations",
      "kind": "line",
      "values": [
        26,
        -119,
        13,
        615
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Items that will not be reclassified subsequently to the income statement",
      "kind": "subtotal",
      "values": [
        26,
        -119,
        13,
        615
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Other comprehensive income",
      "kind": "subtotal",
      "values": [
        -263,
        -1901,
        -1160,
        4778
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Total comprehensive income",
      "kind": "total",
      "values": [
        102171,
        99087,
        82523,
        60303
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    }
  ]
}

export const balanceSheet: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023"
  ],
  "rows": [
    {
      "label": "Intangible assets",
      "kind": "line",
      "values": [
        110208,
        90804,
        60406
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Goodwill",
      "kind": "line",
      "values": [
        19845,
        20017,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Property, plant and equipment",
      "kind": "line",
      "values": [
        208378,
        161680,
        90961
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Investments in associated companies",
      "kind": "line",
      "values": [
        366,
        400,
        410
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Deferred income tax assets",
      "kind": "line",
      "values": [
        23647,
        24648,
        20380
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other receivables and prepayments",
      "kind": "line",
      "values": [
        5864,
        4016,
        1430
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other financial assets",
      "kind": "line",
      "values": [
        2141,
        2277,
        1253
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total non-current assets",
      "kind": "total",
      "values": [
        370449,
        303842,
        174840
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Inventories",
      "kind": "line",
      "values": [
        49623,
        40849,
        31811
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Trade receivables",
      "kind": "line",
      "values": [
        70856,
        71949,
        64770
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Tax receivables",
      "kind": "line",
      "values": [
        4848,
        2853,
        2423
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Marketable securities",
      "kind": "line",
      "values": [
        498,
        10653,
        15838
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Derivative financial instruments",
      "kind": "line",
      "values": [
        6682,
        6326,
        2344
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Cash at bank",
      "kind": "line",
      "values": [
        26464,
        15655,
        14392
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total current assets",
      "kind": "total",
      "values": [
        172453,
        161788,
        139646
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total assets",
      "kind": "total",
      "values": [
        542902,
        465630,
        314486
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Share capital",
      "kind": "line",
      "values": [
        446,
        446,
        451
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Treasury shares",
      "kind": "line",
      "values": [
        -2,
        -2,
        -5
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Retained earnings",
      "kind": "line",
      "values": [
        195298,
        144448,
        104839
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other reserves",
      "kind": "line",
      "values": [
        -1695,
        -1406,
        1276
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total equity",
      "kind": "total",
      "values": [
        194047,
        143486,
        106561
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Borrowings",
      "kind": "line",
      "values": [
        118941,
        89674,
        20528
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Deferred income tax liabilities",
      "kind": "line",
      "values": [
        6611,
        5515,
        10162
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Retirement benefit obligations",
      "kind": "line",
      "values": [
        861,
        903,
        742
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Provisions",
      "kind": "line",
      "values": [
        5730,
        6982,
        6649
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Sales deductions and product returns",
      "kind": "line",
      "values": [
        1051,
        1456,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Total non-current liabilities",
      "kind": "total",
      "values": [
        133194,
        104530,
        38270
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Trade payables",
      "kind": "line",
      "values": [
        19758,
        17140,
        25606
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Tax payables",
      "kind": "line",
      "values": [
        8416,
        9716,
        7116
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other liabilities",
      "kind": "line",
      "values": [
        39721,
        35372,
        189
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total current liabilities",
      "kind": "total",
      "values": [
        215661,
        217614,
        169655
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total liabilities",
      "kind": "total",
      "values": [
        348855,
        322144,
        207925
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total equity and liabilities",
      "kind": "total",
      "values": [
        542902,
        465630,
        314486
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    }
  ]
}

export const cashFlowStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022"
  ],
  "rows": [
    {
      "label": "Net profit",
      "kind": "line",
      "values": [
        102434,
        100988,
        83683,
        55525
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Adjustment of non-cash items:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Income taxes in the income statement",
      "kind": "line",
      "values": [
        28106,
        26203,
        20991,
        13537
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Depreciation, amortisation and impairment losses",
      "kind": "line",
      "values": [
        21982,
        19107,
        9413,
        7362
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Other non-cash items",
      "kind": "line",
      "values": [
        -3122,
        445,
        424,
        22509
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Changes in working capital",
      "kind": "line",
      "values": [
        3737,
        2589,
        19713,
        -5535
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Interest received",
      "kind": "line",
      "values": [
        1398,
        1884,
        1072,
        276
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Interest paid",
      "kind": "line",
      "values": [
        -3419,
        -612,
        -491,
        -272
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Income taxes paid",
      "kind": "line",
      "values": [
        -32014,
        -29636,
        -25897,
        -14515
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Net cash flows from operating activities",
      "kind": "total",
      "values": [
        119102,
        120968,
        108908,
        78887
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Purchase of intangible assets",
      "kind": "line",
      "values": [
        -29973,
        -4145,
        -13090,
        -2607
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Purchase of property, plant and equipment",
      "kind": "line",
      "values": [
        -60140,
        -47164,
        -25806,
        -12146
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Cash used for acquisition of businesses",
      "kind": "line",
      "values": [
        0,
        -82163,
        0,
        -7075
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Settlement for prior year's acquisition of businesses",
      "kind": "line",
      "values": [
        1004,
        0,
        0,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Proceeds from other financial assets",
      "kind": "line",
      "values": [
        30,
        0,
        33,
        0
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Purchase of other financial assets",
      "kind": "line",
      "values": [
        -225,
        -786,
        -271,
        -169
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Purchase of marketable securities",
      "kind": "line",
      "values": [
        -498,
        -19028,
        -13018,
        -9566
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Sale of marketable securities",
      "kind": "line",
      "values": [
        10644,
        24391,
        8260,
        6645
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Net cash flows from investing activities",
      "kind": "total",
      "values": [
        -79158,
        -128895,
        -43892,
        -24918
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Purchase of treasury shares",
      "kind": "line",
      "values": [
        -1388,
        -20181,
        -29924,
        -24086
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Dividends paid",
      "kind": "line",
      "values": [
        -51763,
        -44140,
        -31767,
        -25303
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Proceeds from borrowings",
      "kind": "line",
      "values": [
        103931,
        79391,
        0,
        11215
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Repayment of borrowings",
      "kind": "line",
      "values": [
        -79188,
        -6335,
        -1467,
        -13623
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Net cash flows from financing activities",
      "kind": "total",
      "values": [
        -28408,
        8735,
        -63158,
        -51797
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Net cash generated from activities",
      "kind": "subtotal",
      "values": [
        11536,
        808,
        1858,
        2172
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Cash and cash equivalents at the beginning of the year",
      "kind": "line",
      "values": [
        15655,
        14392,
        12653,
        10719
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Exchange gains/(losses) on cash and cash equivalents",
      "kind": "line",
      "values": [
        -727,
        455,
        -119,
        -238
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Cash and cash equivalents at the end of the year",
      "kind": "line",
      "values": [
        26464,
        15655,
        14392,
        12653
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    }
  ]
}

export default { incomeStatement, balanceSheet, cashFlowStatement, sources, validation }
