// Generated by crawler/src/extract.ts — do not edit by hand.
import type { StatementData } from "@/lib/types"

// The report PDFs these numbers were extracted from.
export const sources = [
  {
    "year": 2025,
    "url": "https://annualreport.novonordisk.com/2025/_assets/downloads/novo-nordisk-annual-report-2025.pdf"
  },
  {
    "year": 2024,
    "url": "https://annualreport.novonordisk.com/2024/_assets/downloads/novo-nordisk-annual-report-2024.pdf"
  },
  {
    "year": 2023,
    "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2024/novo-nordisk-annual-report-2023.pdf"
  },
  {
    "year": 2022,
    "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2023/novo-nordisk-annual-report-2022.pdf"
  },
  {
    "year": 2021,
    "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2022/novo-nordisk-annual-report-2021.pdf"
  },
  {
    "year": 2020,
    "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2021/Novo-Nordisk-Annual-Report-2020.pdf"
  },
  {
    "year": 2019,
    "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/annual-report/pdfs/2019/Novo-Nordisk-Annual-Report-2019.pdf"
  },
  {
    "year": 2018,
    "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2018/NN-AR17_UK_Online1.pdf"
  },
  {
    "year": 2017,
    "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/about-us/pdfs/corporate-governance/annual-general-meetings/agm2018/uk/annual-report-2017.pdf"
  },
  {
    "year": 2016,
    "url": "https://www.novonordisk.com/content/dam/nncorp/global/en/investors/irmaterial/annual_report/2017/20170207_Novo%20Nordisk%20Annual%20Report%202016.pdf"
  }
]

// Cross-statement validation result (accounting identities) at extraction time.
export const validation = {
  "status": "warning",
  "issues": [
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2020",
      "expected": 12757,
      "actual": 12226,
      "diff": -531
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2017",
      "expected": 18852,
      "actual": 17158,
      "diff": -1694
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2016",
      "expected": 18690,
      "actual": 18461,
      "diff": -229
    },
    {
      "check": "ending cash matches (cash flow vs balance sheet)",
      "severity": "warning",
      "period": "2015",
      "expected": 16923,
      "actual": 15850,
      "diff": -1073
    }
  ]
} as const

export const incomeStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014"
  ],
  "rows": [
    {
      "label": "Income statement",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Net sales",
      "kind": "line",
      "values": [
        309064,
        290403,
        232261,
        176954,
        140800,
        126946,
        122021,
        111831,
        111696,
        111780,
        107927,
        88806
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Cost of goods sold",
      "kind": "line",
      "values": [
        -58788,
        -44522,
        -35765,
        -28448,
        -23658,
        -20932,
        -20088,
        17617,
        17632,
        17183,
        16188,
        14562
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Gross profit",
      "kind": "line",
      "values": [
        250276,
        245881,
        196496,
        148506,
        117142,
        106014,
        101933,
        94214,
        94064,
        94597,
        91739,
        74244
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Sales and distribution costs",
      "kind": "line",
      "values": [
        -64310,
        -62101,
        -56743,
        -46217,
        -37008,
        -32928,
        -31823,
        29497,
        28340,
        28377,
        28312,
        23223
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Research and development costs",
      "kind": "line",
      "values": [
        -52039,
        -48062,
        -32443,
        -24047,
        -17772,
        -15462,
        -14220,
        14805,
        14014,
        14563,
        13608,
        13762
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Administrative costs",
      "kind": "line",
      "values": [
        -5969,
        -5276,
        -4855,
        -4467,
        -4050,
        -3958,
        -4007,
        3916,
        3784,
        3962,
        3857,
        3537
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Other operating income and expenses",
      "kind": "line",
      "values": [
        -300,
        -2103,
        119,
        1034,
        332,
        460,
        600,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "label": "Operating profit",
      "kind": "line",
      "values": [
        127658,
        128339,
        102574,
        74809,
        58644,
        54126,
        52483,
        47248,
        48967,
        48432,
        49444,
        34492
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Financial income",
      "kind": "line",
      "values": [
        9660,
        6198,
        2945,
        239,
        2887,
        1628,
        65,
        2122,
        1246,
        92,
        85,
        167
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Financial expenses",
      "kind": "line",
      "values": [
        -6778,
        -7346,
        -845,
        -5986,
        -2451,
        -2624,
        -3995,
        1755,
        1533,
        726,
        6046,
        563
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Profit before income taxes",
      "kind": "line",
      "values": [
        130540,
        127191,
        104674,
        69062,
        59080,
        53130,
        48553,
        47615,
        48680,
        47798,
        43483,
        34096
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Income taxes",
      "kind": "line",
      "values": [
        -28106,
        -26203,
        -20991,
        -13537,
        -11323,
        -10992,
        -9602,
        8987,
        10550,
        9873,
        8623,
        7615
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Net profit",
      "kind": "line",
      "values": [
        102434,
        100988,
        83683,
        55525,
        47757,
        42138,
        38951,
        38628,
        38130,
        37925,
        34860,
        26481
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Earnings per share",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Basic earnings per share (DKK)",
      "kind": "line",
      "values": [
        23.06,
        22.67,
        18.67,
        12.26,
        10.4,
        18.05,
        16.41,
        15.96,
        15.42,
        14.99,
        13.56,
        10.1
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Diluted earnings per share (DKK)",
      "kind": "line",
      "values": [
        23.03,
        22.63,
        18.62,
        12.22,
        10.37,
        18.01,
        16.38,
        15.93,
        15.39,
        14.96,
        13.52,
        10.07
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Statement of comprehensive income",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Other comprehensive income:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Exchange rate adjustments of investments in subsidiaries",
      "kind": "line",
      "values": [
        -7759,
        3096,
        -1404,
        2289,
        1624,
        -1689,
        226,
        491,
        -632,
        -7,
        -669,
        -39
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Cash flow hedges:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Realisation of previously deferred (gains)/losses",
      "kind": "line",
      "values": [
        5763,
        -1612,
        -1026,
        1740,
        -1802,
        329,
        1677,
        -2027,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Deferred gains/(losses) related to acquisition of businesses",
      "kind": "line",
      "values": [
        null,
        1154,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Deferred gains/(losses) on hedges open at year-end",
      "kind": "line",
      "values": [
        4339,
        -5763,
        1612,
        1026,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Tax and other items",
      "kind": "line",
      "values": [
        -2632,
        1343,
        -355,
        -892,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Items that will be reclassified subsequently to the income statement",
      "kind": "line",
      "values": [
        -289,
        -1782,
        -1173,
        4163,
        -816,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Remeasurements of retirement benefit obligations",
      "kind": "section",
      "values": [
        null,
        -119,
        13,
        615,
        146,
        -67,
        -187,
        87,
        103,
        -205,
        -37,
        null
      ],
      "restatedIndices": [
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Items that will not be reclassified subsequently to the income statement",
      "kind": "line",
      "values": [
        -119,
        13,
        13,
        615,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Other comprehensive income",
      "kind": "subtotal",
      "values": [
        -263,
        -1901,
        -1160,
        4778,
        -670,
        -610,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4
      ]
    },
    {
      "label": "Total comprehensive income",
      "kind": "total",
      "values": [
        102171,
        99087,
        82523,
        60303,
        47087,
        41528,
        40116,
        36230,
        39925,
        36734,
        35968,
        23829
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Deferred gains/(losses) incurred during the period",
      "kind": "line",
      "values": [
        null,
        null,
        1612,
        1026,
        -1755,
        1384,
        -329,
        -1677,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Other items",
      "kind": "line",
      "values": [
        null,
        null,
        4,
        -3,
        112,
        10,
        9,
        -27,
        -577,
        -74,
        366,
        111
      ],
      "unit": "currency",
      "restatedIndices": [
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Income tax related to these items",
      "kind": "line",
      "values": [
        null,
        null,
        -359,
        -889,
        1005,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Items that will not be reclassified subsequently to the income statement:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Items that will be reclassified subsequently to the income statement:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Tax on other comprehensive income, net",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        -889,
        1005,
        -577,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Tax on other comprehensive income, income/(expense)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        1005,
        -577,
        -231,
        755,
        -1041,
        324,
        -87,
        977
      ],
      "unit": "currency",
      "restatedIndices": [
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Other comprehensive income, net of tax",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        -670,
        -610,
        1165,
        -2398,
        1795,
        -1191,
        1108,
        -2652
      ],
      "unit": "currency",
      "restatedIndices": [
        5,
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Other operating income, net",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        460,
        600,
        1152,
        1041,
        737,
        3482,
        770
      ],
      "unit": "currency",
      "restatedIndices": [
        6,
        7,
        8,
        9,
        10
      ]
    },
    {
      "label": "Cash flow hedges, realisation of previously deferred (gains)/losses",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        1677,
        -2027,
        1955,
        682,
        2216,
        -1229
      ],
      "restatedIndices": [
        8,
        9,
        10
      ]
    },
    {
      "label": "Cash flow hedges, deferred gains/(losses) incurred during the period",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -329,
        -1677,
        1987,
        -1911,
        -681,
        -2225
      ],
      "restatedIndices": [
        8,
        9,
        10
      ]
    },
    {
      "label": "INCOME STATEMENT",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "– Non-recurring income from the partial divestment of NNIT A/S",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2376,
        null
      ],
      "restatedIndices": [
        10
      ]
    },
    {
      "label": "EARNINGS PER SHARE",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "STATEMENT OF COMPREHENSIVE INCOME",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Items that will not be reclassified subsequently to the Income statement:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Items that will be reclassified subsequently to the Income statement:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Remeasurements of defined benefit plans",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -205,
        -37,
        -247
      ],
      "unit": "currency"
    }
  ]
}

export const balanceSheet: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015"
  ],
  "rows": [
    {
      "label": "Assets",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Intangible assets",
      "kind": "line",
      "values": [
        110208,
        90804,
        60406,
        51416,
        43171,
        20657,
        5835,
        5145,
        3325,
        2714,
        2158
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Goodwill",
      "kind": "line",
      "values": [
        19845,
        20017,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Property, plant and equipment",
      "kind": "line",
      "values": [
        208378,
        161680,
        90961,
        66671,
        55362,
        50269,
        50551,
        41891,
        35247,
        30179,
        25545
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Investments in associated companies",
      "kind": "line",
      "values": [
        366,
        400,
        410,
        327,
        525,
        582,
        474,
        531,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6
      ]
    },
    {
      "label": "Deferred income tax assets",
      "kind": "line",
      "values": [
        23647,
        24648,
        20380,
        13427,
        8672,
        5865,
        4121,
        2893,
        1941,
        2683,
        6806
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Other receivables and prepayments",
      "kind": "line",
      "values": [
        5864,
        4016,
        1430,
        206,
        267,
        674,
        841,
        null,
        2428,
        2411,
        2257
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Other financial assets",
      "kind": "line",
      "values": [
        2141,
        2277,
        1253,
        1016,
        916,
        1066,
        1334,
        1242,
        978,
        1388,
        1339
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Total non-current assets",
      "kind": "subtotal",
      "values": [
        370449,
        303842,
        174840,
        133063,
        108913,
        79113,
        63156,
        51702,
        42275,
        37773,
        36659
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Inventories",
      "kind": "line",
      "values": [
        49623,
        40849,
        31811,
        24388,
        19621,
        18536,
        17641,
        16336,
        15373,
        14341,
        12758
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Trade receivables",
      "kind": "line",
      "values": [
        70856,
        71949,
        64770,
        50560,
        40643,
        27734,
        24912,
        22786,
        20165,
        20234,
        15485
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Tax receivables",
      "kind": "line",
      "values": [
        4848,
        2853,
        2423,
        940,
        1119,
        289,
        806,
        1013,
        958,
        1552,
        3871
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Marketable securities",
      "kind": "line",
      "values": [
        498,
        10653,
        15838,
        10921,
        6765,
        null,
        null,
        null,
        null,
        2009,
        3542
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        9
      ]
    },
    {
      "label": "Derivative financial instruments",
      "kind": "line",
      "values": [
        6682,
        6326,
        2344,
        2727,
        1690,
        2332,
        734,
        204,
        2304,
        529,
        304
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Cash at bank",
      "kind": "line",
      "values": [
        26464,
        15655,
        14392,
        12653,
        10720,
        12757,
        15475,
        15638,
        18852,
        18690,
        16923
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Total current assets",
      "kind": "subtotal",
      "values": [
        172453,
        161788,
        139646,
        108194,
        85595,
        65809,
        62456,
        59067,
        60080,
        59766,
        55140
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Total assets",
      "kind": "total",
      "values": [
        542902,
        465630,
        314486,
        241257,
        194508,
        144922,
        125612,
        110769,
        102355,
        97539,
        91799
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Equity and liabilities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Share capital",
      "kind": "line",
      "values": [
        446,
        446,
        451,
        456,
        462,
        470,
        480,
        490,
        500,
        510,
        520
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Treasury shares",
      "kind": "line",
      "values": [
        -2,
        -2,
        -5,
        -6,
        -6,
        -8,
        -10,
        -11,
        -11,
        -9,
        -10
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Retained earnings",
      "kind": "line",
      "values": [
        195298,
        144448,
        104839,
        80587,
        72004,
        63774,
        57817,
        53406,
        48977,
        46111,
        46816
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Other reserves",
      "kind": "line",
      "values": [
        -1695,
        -1406,
        1276,
        2449,
        -1714,
        -911,
        -694,
        -2046,
        349,
        -1343,
        -357
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Total equity",
      "kind": "subtotal",
      "values": [
        194047,
        143486,
        106561,
        83486,
        70746,
        63325,
        57593,
        51839,
        49815,
        45269,
        46969
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Borrowings",
      "kind": "line",
      "values": [
        118941,
        89674,
        20528,
        24318,
        12961,
        2897,
        3009,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6
      ]
    },
    {
      "label": "Deferred income tax liabilities",
      "kind": "line",
      "values": [
        6611,
        5515,
        10162,
        7061,
        5271,
        2502,
        80,
        118,
        846,
        13,
        6
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Retirement benefit obligations",
      "kind": "line",
      "values": [
        861,
        903,
        742,
        762,
        1280,
        1399,
        1334,
        1256,
        1336,
        1451,
        1186
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Provisions",
      "kind": "line",
      "values": [
        5730,
        6982,
        6649,
        4590,
        4374,
        4526,
        4613,
        3392,
        3302,
        3370,
        2765
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Sales deductions and product returns",
      "kind": "line",
      "values": [
        1051,
        1456,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Total non-current liabilities",
      "kind": "subtotal",
      "values": [
        133194,
        104530,
        38270,
        36831,
        24246,
        11324,
        9036,
        4766,
        5484,
        4834,
        3957
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Trade payables",
      "kind": "line",
      "values": [
        19758,
        17140,
        25606,
        15587,
        8870,
        5717,
        6358,
        6756,
        5610,
        6011,
        4927
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Tax payables",
      "kind": "line",
      "values": [
        8416,
        9716,
        7116,
        7091,
        3658,
        3913,
        4212,
        4610,
        4242,
        3976,
        3777
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Other liabilities",
      "kind": "line",
      "values": [
        39721,
        35372,
        189,
        100,
        360,
        17005,
        15085,
        14098,
        14446,
        14181,
        12655
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        6,
        8,
        9
      ]
    },
    {
      "label": "Total current liabilities",
      "kind": "subtotal",
      "values": [
        215661,
        217614,
        169655,
        120940,
        99516,
        70273,
        58983,
        54164,
        47056,
        47436,
        40873
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Total liabilities",
      "kind": "total",
      "values": [
        348855,
        322144,
        207925,
        157771,
        123762,
        81597,
        68019,
        58930,
        52540,
        52270,
        44830
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Total equity and liabilities",
      "kind": "total",
      "values": [
        542902,
        465630,
        314486,
        241257,
        194508,
        144922,
        125612,
        110769,
        102355,
        97539,
        91799
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        4,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "ASSETS",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Investment in associated company",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        784,
        809,
        811
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "EQUITY AND LIABILITIES",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Current debt",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        1694,
        229,
        1073
      ],
      "restatedIndices": [
        8,
        9
      ]
    }
  ]
}

export const cashFlowStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014"
  ],
  "rows": [
    {
      "label": "Net profit",
      "kind": "line",
      "values": [
        102434,
        100988,
        83683,
        55525,
        47757,
        42138,
        38951,
        38628,
        38130,
        37925,
        34860,
        26481
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Adjustment of non-cash items:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Income taxes in the income statement",
      "kind": "line",
      "values": [
        28106,
        26203,
        20991,
        13537,
        11323,
        10992,
        9602,
        8987,
        10550,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Depreciation, amortisation and impairment losses",
      "kind": "line",
      "values": [
        21982,
        19107,
        9413,
        7362,
        6025,
        5753,
        5661,
        3925,
        3182,
        3193,
        2959,
        3435
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Other non-cash items1",
      "kind": "line",
      "values": [
        -3122,
        445,
        424,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Changes in working capital1",
      "kind": "line",
      "values": [
        3737,
        2589,
        19713,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Interest received",
      "kind": "line",
      "values": [
        1398,
        1884,
        1072,
        276,
        241,
        100,
        64,
        51,
        101,
        114,
        55,
        131
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Interest paid",
      "kind": "line",
      "values": [
        -3419,
        -612,
        -491,
        -272,
        -261,
        -422,
        -204,
        -89,
        -87,
        -66,
        -61,
        -78
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Income taxes paid",
      "kind": "line",
      "values": [
        -32014,
        -29636,
        -25897,
        -14515,
        -14438,
        -10106,
        -10936,
        -9614,
        -9101,
        -2899,
        -9374,
        -7907
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Net cash flows from operating activities",
      "kind": "total",
      "values": [
        119102,
        120968,
        108908,
        78887,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Purchase of intangible assets",
      "kind": "line",
      "values": [
        -29973,
        -4145,
        -13090,
        -2607,
        -1050,
        -16256,
        -2299,
        -2774,
        -1022,
        -1199,
        -1182,
        -321
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Purchase of property, plant and equipment",
      "kind": "line",
      "values": [
        -60140,
        -47164,
        -25806,
        -12146,
        -6335,
        -5825,
        -8932,
        -9636,
        -7626,
        -7068,
        -5224,
        -3990
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Cash used for acquisition of businesses",
      "kind": "line",
      "values": [
        null,
        -82163,
        null,
        -7075,
        -18283,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        3,
        4
      ]
    },
    {
      "label": "Settlement for prior year's acquisition of businesses",
      "kind": "line",
      "values": [
        1004,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Proceeds from other financial assets",
      "kind": "line",
      "values": [
        30,
        null,
        33,
        null,
        null,
        12,
        148,
        178,
        73,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        5,
        6
      ]
    },
    {
      "label": "Purchase of other financial assets",
      "kind": "line",
      "values": [
        -225,
        -786,
        -271,
        -169,
        -4,
        null,
        -350,
        -248,
        -40,
        -112,
        -9,
        -24
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Purchase of marketable securities",
      "kind": "line",
      "values": [
        -498,
        -19028,
        -13018,
        -9566,
        -7109,
        null,
        null,
        null,
        null,
        -531,
        -3533,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        9,
        10
      ]
    },
    {
      "label": "Sale of marketable securities",
      "kind": "line",
      "values": [
        10644,
        24391,
        8260,
        6645,
        1172,
        null,
        null,
        null,
        2009,
        2064,
        1500,
        2232
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        8,
        9,
        10
      ]
    },
    {
      "label": "Net cash flows from investing activities",
      "kind": "total",
      "values": [
        -79158,
        -128895,
        -43892,
        -24918,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Purchase of treasury shares",
      "kind": "line",
      "values": [
        -1388,
        -20181,
        -29924,
        -24086,
        -19447,
        -16855,
        -15334,
        -15567,
        -16845,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6
      ]
    },
    {
      "label": "Dividends paid",
      "kind": "line",
      "values": [
        -51763,
        -44140,
        -31767,
        -25303,
        -21517,
        -20121,
        -19409,
        -19048,
        -18844,
        -23830,
        -12905,
        -11866
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Proceeds from borrowings",
      "kind": "line",
      "values": [
        103931,
        79391,
        null,
        11215,
        22160,
        5682,
        81,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        3,
        4,
        5
      ]
    },
    {
      "label": "Repayment of borrowings",
      "kind": "line",
      "values": [
        -79188,
        -6335,
        -1467,
        -13623,
        -6689,
        -950,
        -822,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "label": "Net cash flows from financing activities",
      "kind": "total",
      "values": [
        -28408,
        8735,
        -63158,
        -51797,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Net cash generated from activities",
      "kind": "line",
      "values": [
        11536,
        808,
        1858,
        2172,
        -2098,
        -2729,
        -211,
        -1985,
        -1092,
        2637,
        2088,
        3095
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Cash and cash equivalents at the beginning of the year",
      "kind": "line",
      "values": [
        15655,
        14392,
        12653,
        10719,
        12226,
        15411,
        15629,
        17158,
        18461,
        15850,
        13676,
        10513
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Exchange gains/(losses) on cash and cash equivalents",
      "kind": "line",
      "values": [
        -727,
        455,
        -119,
        -238,
        591,
        -456,
        -7,
        44,
        -211,
        -26,
        86,
        68
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Cash and cash equivalents at the end of the year",
      "kind": "total",
      "values": [
        26464,
        15655,
        14392,
        12653,
        10719,
        12226,
        15411,
        15629,
        17158,
        18461,
        15850,
        13676
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Other non-cash items",
      "kind": "line",
      "values": [
        null,
        15029,
        33517,
        22509,
        13416,
        7849,
        7032,
        6098,
        2027,
        3882,
        5908,
        4163
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Changes in working capital",
      "kind": "line",
      "values": [
        null,
        -11995,
        -13380,
        -5535,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Change in working capital",
      "kind": "line",
      "values": [
        null,
        null,
        -12245,
        -5336,
        -9063,
        -4353,
        -3388,
        -3370,
        -3634,
        -3708,
        -2157,
        -2148
      ],
      "restatedIndices": [
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Net cash generated from operating activities",
      "kind": "line",
      "values": [
        null,
        null,
        108908,
        78887,
        55000,
        51951,
        46782,
        44616,
        41168,
        48314,
        38287,
        31692
      ],
      "restatedIndices": [
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Dividend received from associated companies",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        4,
        18,
        20,
        19,
        26,
        null,
        null,
        null
      ],
      "restatedIndices": [
        4,
        5,
        6
      ]
    },
    {
      "label": "Net cash used in investing activities",
      "kind": "line",
      "values": [
        null,
        null,
        -43892,
        -24918,
        -31605,
        -22436,
        -11509,
        -12080,
        -6571,
        -6790,
        -6098,
        -2064
      ],
      "restatedIndices": [
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Net cash used in financing activities",
      "kind": "line",
      "values": [
        null,
        null,
        -63158,
        -51797,
        -25493,
        -32244,
        -35484,
        -34521,
        -35689,
        -38887,
        -30101,
        -26533
      ],
      "restatedIndices": [
        3,
        4,
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Proceeds from sale of property, plant and equipment",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        7,
        4,
        9,
        9,
        7,
        15,
        4
      ],
      "restatedIndices": [
        5,
        6,
        8,
        9,
        10
      ]
    },
    {
      "label": "Investment in associated companies",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -392,
        -97,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        5,
        6
      ]
    },
    {
      "label": "Proceeds from the divestment of Group and associated companies",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -3,
        368,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        6
      ]
    },
    {
      "label": "Gross sales",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        298187,
        270431,
        230701,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "US Managed Care and Medicare",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -96716,
        -84202,
        -65207,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "US wholesaler charge-backs",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -37036,
        -33772,
        -29469,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "US Medicaid rebates",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -17307,
        -14365,
        -11950,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Other US discounts and sales returns",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -10867,
        -8280,
        -6606,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Non-US rebates, discounts and sales returns",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -9315,
        -7791,
        -5638,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Total gross-to-net sales adjustments",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -171241,
        -148410,
        -118870,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Net sales",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        126946,
        122021,
        111831,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "At the beginning of the year",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        30878,
        25760,
        20374,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Additional provisions, including increases to existing provisions",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        111921,
        102782,
        82631,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Amount paid during the year",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -106116,
        -98655,
        -78647,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Adjustments, including unused amounts reversed during the year",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        166,
        381,
        386,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Effect of exchange rate adjustment",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        -2797,
        610,
        1016,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "At the end of the year",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        34052,
        30878,
        25760,
        null,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Repayment of borrowings, net",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        -741,
        94,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Reclassification of bank overdraft to financing activities",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        412,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "CASH FLOW STATEMENT",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Reversal of non-cash items:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Income taxes in the Income statement",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        10550,
        9873,
        8623,
        null
      ],
      "restatedIndices": [
        8,
        9,
        10
      ]
    },
    {
      "label": "Non-recurring income from the partial divestment of NNIT A/S included in Other operating income",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -2526,
        null
      ],
      "restatedIndices": [
        10
      ]
    },
    {
      "label": "Proceeds from the partial divestment of NNIT A/S",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        2303,
        null
      ],
      "restatedIndices": [
        10
      ]
    },
    {
      "label": "Proceeds from sale of other financial assets",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        73,
        23,
        32,
        35
      ],
      "restatedIndices": [
        8,
        9,
        10
      ]
    },
    {
      "label": "Dividend received from associated company",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        26,
        26,
        null,
        null
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Purchase of treasury shares, net",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -16845,
        -15057,
        -17196,
        -14667
      ],
      "restatedIndices": [
        8,
        9,
        10
      ]
    },
    {
      "label": "Income taxes in Income statement",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        9873,
        8623,
        7615
      ]
    }
  ]
}

export default { incomeStatement, balanceSheet, cashFlowStatement, sources, validation }
