// Generated by crawler/src/extract.ts — do not edit by hand.
import type { StatementData } from "@/lib/types"

// The report PDFs these numbers were extracted from.
export const sources = [
  {
    "year": 2025,
    "url": "https://www.rheinmetall.com/Rheinmetall%20Group/Investor%20Relations/Ver%C3%B6ffentlichungen/Pr%C3%A4sentationen%20und%20Berichte/2026/GB/Rheinmetall-Annual-Report-2025.pdf"
  },
  {
    "year": 2024,
    "url": "https://www.rheinmetall.com/Rheinmetall%20Group/Investor%20Relations/Ver%C3%B6ffentlichungen/Pr%C3%A4sentationen%20und%20Berichte/2025/GB/Rheinmetall-Annual-Report-2024.pdf"
  }
]

export const incomeStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023"
  ],
  "rows": [
    {
      "label": "Investment income",
      "kind": "line",
      "values": [
        566,
        637,
        567
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Income from loans of non-current financial assets",
      "kind": "line",
      "values": [
        8,
        0,
        null
      ]
    },
    {
      "label": "Net interest",
      "kind": "line",
      "values": [
        -23,
        -46,
        -18
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Net financial income",
      "kind": "line",
      "values": [
        551,
        591,
        549
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Sales",
      "kind": "line",
      "values": [
        156,
        110,
        84
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other operating income",
      "kind": "line",
      "values": [
        213,
        274,
        221
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Personnel expenses",
      "kind": "line",
      "values": [
        91,
        69,
        63
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Amortization, depreciation and write-downs",
      "kind": "line",
      "values": [
        6,
        4,
        8
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other operating expenses",
      "kind": "line",
      "values": [
        315,
        366,
        292
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Earnings before taxes (EBT)",
      "kind": "subtotal",
      "values": [
        508,
        535,
        null
      ]
    },
    {
      "label": "Taxes on income and revenue",
      "kind": "line",
      "values": [
        -195,
        -88,
        -99
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Net profit for the year",
      "kind": "subtotal",
      "values": [
        314,
        447,
        393
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Allocation to retained earnings",
      "kind": "line",
      "values": [
        0,
        67,
        null
      ]
    },
    {
      "label": "Withdrawal from retained earnings",
      "kind": "line",
      "values": [
        235,
        0,
        null
      ]
    },
    {
      "label": "Net earnings",
      "kind": "total",
      "values": [
        549,
        380,
        250
      ],
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Earnings before Taxes (EBT)",
      "kind": "subtotal",
      "values": [
        null,
        535,
        491
      ],
      "unit": "currency"
    },
    {
      "label": "Appropriations to retained earnings",
      "kind": "line",
      "values": [
        null,
        67,
        143
      ],
      "unit": "currency"
    }
  ]
}

export const balanceSheet: StatementData = {
  "periods": [
    "12/31/2025",
    "12/31/2024",
    "2023"
  ],
  "rows": [
    {
      "label": "Non-current assets",
      "kind": "line",
      "values": [
        5871,
        6112,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Current assets",
      "kind": "line",
      "values": [
        10901,
        8231,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Total assets",
      "kind": "total",
      "values": [
        16772,
        14344,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Equity",
      "kind": "line",
      "values": [
        5614,
        4465,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Non-current liabilities",
      "kind": "line",
      "values": [
        2086,
        3097,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Current liabilities",
      "kind": "line",
      "values": [
        9071,
        6782,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Total equity and liabilities",
      "kind": "total",
      "values": [
        16772,
        14344,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Current financial debts",
      "kind": "line",
      "values": [
        126,
        552,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Non-current financial debts",
      "kind": "line",
      "values": [
        1155,
        1871,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Total financial debts",
      "kind": "subtotal",
      "values": [
        1281,
        2423,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Cash and cash equivalents",
      "kind": "line",
      "values": [
        1650,
        1184,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Net financial debts (-)/Net liquidity (+)",
      "kind": "line",
      "values": [
        369,
        -1239,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Net financial debts (-)/Net liquidity (+) from continuing operations",
      "kind": "line",
      "values": [
        369,
        -1292,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Total assets adjusted for cash and cash equivalents",
      "kind": "line",
      "values": [
        15122,
        13159,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Net financial debts (-)",
      "kind": "line",
      "values": [
        369,
        -1292,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Assets from pension valuation",
      "kind": "line",
      "values": [
        289,
        275,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Pension provisions",
      "kind": "line",
      "values": [
        278,
        325,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Capital employed",
      "kind": "line",
      "values": [
        5235,
        5807,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Average capital employed",
      "kind": "line",
      "values": [
        5521,
        5425,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "EBIT pre PPA effect",
      "kind": "line",
      "values": [
        1850,
        1395,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "ROCE (in %)",
      "kind": "line",
      "values": [
        33.5,
        25.7,
        null
      ],
      "decimals": 2
    },
    {
      "label": "Present value of DBO",
      "kind": "line",
      "values": [
        null,
        2338,
        2323
      ]
    },
    {
      "label": "Plan assets (at fair value)",
      "kind": "line",
      "values": [
        null,
        -2121,
        -2031
      ]
    },
    {
      "label": "Net liability for defined benefit obligations",
      "kind": "line",
      "values": [
        null,
        217,
        291
      ]
    },
    {
      "label": "As of 1/1",
      "kind": "line",
      "values": [
        null,
        2323,
        2088
      ]
    },
    {
      "label": "Current service cost",
      "kind": "line",
      "values": [
        null,
        35,
        28
      ]
    },
    {
      "label": "Past service cost",
      "kind": "line",
      "values": [
        null,
        null,
        null
      ]
    },
    {
      "label": "Interest cost",
      "kind": "line",
      "values": [
        null,
        57,
        62
      ]
    },
    {
      "label": "Interest income",
      "kind": "line",
      "values": [
        null,
        null,
        null
      ]
    },
    {
      "label": "Entry benefits/leaving benefits",
      "kind": "line",
      "values": [
        null,
        null,
        null
      ]
    },
    {
      "label": "Amounts recognized in the income statement",
      "kind": "line",
      "values": [
        null,
        93,
        90
      ]
    },
    {
      "label": "Expense (income) from plan assets (excluding interest income)",
      "kind": "line",
      "values": [
        null,
        -63,
        -42
      ]
    },
    {
      "label": "Actuarial gains (-) and losses (+) Change in financial assumptions",
      "kind": "line",
      "values": [
        null,
        11,
        131
      ]
    },
    {
      "label": "Actuarial gains (-) and losses (+) Change in demographic assumptions",
      "kind": "line",
      "values": [
        null,
        -5,
        null
      ]
    },
    {
      "label": "Actuarial gains (-) and losses (+) Empirical adjustments",
      "kind": "line",
      "values": [
        null,
        -14,
        7
      ]
    },
    {
      "label": "Other comprehensive income from remeasurement of net defined benefit",
      "kind": "line",
      "values": [
        null,
        -72,
        96
      ]
    },
    {
      "label": "Employer contributions",
      "kind": "line",
      "values": [
        null,
        -26,
        -30
      ]
    },
    {
      "label": "Employee contributions",
      "kind": "line",
      "values": [
        null,
        1,
        -1
      ]
    },
    {
      "label": "Pension payments",
      "kind": "line",
      "values": [
        null,
        -44,
        -36
      ]
    },
    {
      "label": "Adjustment in scope of consolidation",
      "kind": "line",
      "values": [
        null,
        1,
        null
      ]
    },
    {
      "label": "Reclassification IFRS 5",
      "kind": "line",
      "values": [
        null,
        15,
        40
      ]
    },
    {
      "label": "Currency differences/Other",
      "kind": "line",
      "values": [
        null,
        2,
        -2
      ]
    },
    {
      "label": "As of 12/31",
      "kind": "line",
      "values": [
        null,
        217,
        291
      ]
    },
    {
      "label": "Defined benefit obligation",
      "kind": "line",
      "values": [
        null,
        2338,
        2323
      ]
    },
    {
      "label": "Plan assets",
      "kind": "line",
      "values": [
        null,
        -2121,
        -2031
      ]
    },
    {
      "label": "Changes in the effect of the asset ceiling",
      "kind": "line",
      "values": [
        null,
        36,
        172
      ]
    },
    {
      "label": "Balance sheet amount",
      "kind": "line",
      "values": [
        null,
        253,
        463
      ]
    },
    {
      "label": "thereof provision",
      "kind": "line",
      "values": [
        null,
        528,
        562
      ]
    },
    {
      "label": "thereof net asset value",
      "kind": "line",
      "values": [
        null,
        275,
        99
      ]
    }
  ]
}

export const cashFlowStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023"
  ],
  "rows": [
    {
      "label": "Earnings after taxes",
      "kind": "line",
      "values": [
        835,
        808,
        586
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Amortization/depreciation/impairment of property, plant and equipment, intangible assets and investment property",
      "kind": "line",
      "values": [
        501,
        403,
        308
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Impairment/reversal of impairment of non-current assets of discontinued operations",
      "kind": "line",
      "values": [
        376,
        0,
        63
      ],
      "unit": "currency"
    },
    {
      "label": "Allocation of CTA assets to secure pension and partial retirement obligations",
      "kind": "line",
      "values": [
        -28,
        -18,
        -20
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other changes in pension provisions",
      "kind": "line",
      "values": [
        4,
        -6,
        -48
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Income/expenses from disposals of non-current assets and disinvestments in consolidated companies",
      "kind": "line",
      "values": [
        -24,
        103,
        -59
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Changes in other provisions",
      "kind": "line",
      "values": [
        117,
        135,
        29
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Changes in working capital",
      "kind": "line",
      "values": [
        499,
        407,
        -217
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Changes in receivables, liabilities (without financial debt) and prepaid and deferred items",
      "kind": "line",
      "values": [
        93,
        -102,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Pro rata income/loss from investments accounted for using the equity method",
      "kind": "line",
      "values": [
        -9,
        15,
        -4
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Dividends received from investments accounted for using the equity method",
      "kind": "line",
      "values": [
        21,
        16,
        29
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other non-cash expenses and income",
      "kind": "line",
      "values": [
        -97,
        -42,
        28
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Cash flow from operating activities",
      "kind": "total",
      "values": [
        2287,
        1720,
        743
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Of which continuing operations",
      "kind": "subtotal",
      "values": [
        1996,
        1625,
        740
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Of which discontinued operations",
      "kind": "subtotal",
      "values": [
        291,
        95,
        3
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Cash outflows for property, plant and equipment, intangible assets and investment property",
      "kind": "line",
      "values": [
        -872,
        -732,
        -398
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Cash inflows from government grants for investments not yet commenced",
      "kind": "line",
      "values": [
        null,
        35,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Cash inflows from the disposal of property, plant and equipment, intangible assets and investment property",
      "kind": "line",
      "values": [
        10,
        10,
        2
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Cash inflows/outflows from disinvestments in consolidated companies and financial assets",
      "kind": "line",
      "values": [
        74,
        24,
        155
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Cash outflows for investments in consolidated companies and financial assets",
      "kind": "line",
      "values": [
        -54,
        -508,
        -1064
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Cash flow from investing activities",
      "kind": "total",
      "values": [
        -843,
        -1172,
        -1175
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Dividends paid out by Rheinmetall AG",
      "kind": "line",
      "values": [
        -369,
        -248,
        -187
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Other profit distributions",
      "kind": "line",
      "values": [
        -52,
        -29,
        -3
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Increase in shares in consolidated subsidiaries",
      "kind": "line",
      "values": [
        75,
        22,
        21
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Borrowing of other financial debts",
      "kind": "line",
      "values": [
        71,
        793,
        407
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Repayment of other financial debts",
      "kind": "line",
      "values": [
        -585,
        -773,
        -485
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Cash flow from financing activities",
      "kind": "total",
      "values": [
        -861,
        -234,
        746
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Changes in cash and cash equivalents",
      "kind": "line",
      "values": [
        583,
        313,
        314
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Changes in cash and cash equivalents due to exchange rates",
      "kind": "line",
      "values": [
        -10,
        -2,
        -9
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Total change in cash and cash equivalents",
      "kind": "total",
      "values": [
        574,
        312,
        305
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Opening cash and cash equivalents January 1",
      "kind": "line",
      "values": [
        1184,
        873,
        568
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Closing cash and cash equivalents December 31",
      "kind": "line",
      "values": [
        1758,
        1184,
        873
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Closing cash and cash equivalents December 31 from discontinued operations",
      "kind": "line",
      "values": [
        108,
        0,
        23
      ],
      "unit": "currency"
    },
    {
      "label": "Cash and cash equivalents as per consolidated statement of financial position December 31",
      "kind": "line",
      "values": [
        1650,
        1184,
        850
      ],
      "unit": "currency",
      "restatedIndices": [
        1
      ]
    },
    {
      "label": "Proceeds from reimbursements of pension payments made from CTA assets",
      "kind": "line",
      "values": [
        null,
        0,
        8
      ],
      "unit": "currency"
    },
    {
      "label": "Changes in receivables, liabilities (without financial debt) and prepaid & deferred items",
      "kind": "line",
      "values": [
        null,
        -102,
        39
      ],
      "unit": "currency"
    },
    {
      "label": "Cash inflows from government grants for investments",
      "kind": "line",
      "values": [
        null,
        35,
        0
      ],
      "unit": "currency"
    },
    {
      "label": "Cash in-/outflows from/for securities held for trade",
      "kind": "line",
      "values": [
        null,
        0,
        130
      ],
      "unit": "currency"
    },
    {
      "label": "Cash inflows from the issuance of convertible bonds - Addition to equity",
      "kind": "line",
      "values": [
        null,
        0,
        113
      ],
      "unit": "currency"
    },
    {
      "label": "Cash inflows from the issuance of convertible bonds - Fair value financial liability",
      "kind": "line",
      "values": [
        null,
        0,
        887
      ],
      "unit": "currency"
    },
    {
      "label": "Transaction costs for the issuance of convertible bonds",
      "kind": "line",
      "values": [
        null,
        0,
        -7
      ],
      "unit": "currency"
    }
  ]
}

export default { incomeStatement, balanceSheet, cashFlowStatement, sources }
