// Generated by crawler/src/extract.ts — do not edit by hand.
import type { StatementData } from "@/lib/types"

// The report PDFs these numbers were extracted from.
export const sources = [
  {
    "year": 2025,
    "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-integrated-report.pdf"
  },
  {
    "year": 2024,
    "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-integrated-report.pdf"
  },
  {
    "year": 2023,
    "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-integrated-report.pdf"
  }
]

export const incomeStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021"
  ],
  "rows": [
    {
      "label": "Cloud",
      "kind": "line",
      "values": [
        21023,
        17141,
        13664,
        11426,
        8701
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Software licenses",
      "kind": "line",
      "values": [
        990,
        1399,
        1764,
        2056,
        3248
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Software support",
      "kind": "line",
      "values": [
        10525,
        11290,
        11496,
        11909,
        11412
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Software licenses and support",
      "kind": "subtotal",
      "values": [
        11515,
        12689,
        13261,
        13965,
        14660
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Cloud and software",
      "kind": "subtotal",
      "values": [
        32538,
        29830,
        26924,
        25391,
        23361
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Services",
      "kind": "line",
      "values": [
        4262,
        4346,
        4283,
        4128,
        3592
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Total revenue",
      "kind": "total",
      "values": [
        36800,
        34176,
        31207,
        29520,
        26953
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Cost of cloud",
      "kind": "line",
      "values": [
        -5480,
        -4660,
        -3884,
        -3499,
        -2881
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Cost of software licenses and support",
      "kind": "line",
      "values": [
        -1313,
        -1262,
        -1383,
        -1384,
        -1598
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Cost of cloud and software",
      "kind": "subtotal",
      "values": [
        -6793,
        -5922,
        -5267,
        -4883,
        -4479
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Cost of services",
      "kind": "line",
      "values": [
        -3193,
        -3321,
        -3407,
        -3155,
        -2740
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Total cost of revenue",
      "kind": "total",
      "values": [
        -9986,
        -9243,
        -8674,
        -8038,
        -7219
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Gross profit",
      "kind": "line",
      "values": [
        26814,
        24932,
        22534,
        21482,
        19734
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Research and development",
      "kind": "line",
      "values": [
        -6633,
        -6514,
        -6324,
        -6080,
        -5270
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Sales and marketing",
      "kind": "line",
      "values": [
        -8879,
        -9090,
        -8828,
        -7946,
        -6856
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "General and administration",
      "kind": "line",
      "values": [
        -1633,
        -1435,
        -1364,
        -1289,
        -1187
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Restructuring",
      "kind": "line",
      "values": [
        -3,
        -3144,
        -215,
        -138,
        -157
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Other operating income/expense, net",
      "kind": "line",
      "values": [
        -49,
        -85,
        -4,
        -116,
        44
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Total operating expenses",
      "kind": "total",
      "values": [
        -27183,
        -29511,
        -25408,
        -23606,
        -20645
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Operating profit",
      "kind": "line",
      "values": [
        9617,
        4665,
        5799,
        5914,
        6308
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Other non-operating income/expense, net",
      "kind": "line",
      "values": [
        118,
        -298,
        -3,
        -11,
        19
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Finance income",
      "kind": "line",
      "values": [
        1911,
        1429,
        857,
        811,
        3123
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Finance costs",
      "kind": "line",
      "values": [
        -1377,
        -1031,
        -1313,
        -2200,
        -945
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Financial income, net",
      "kind": "line",
      "values": [
        534,
        398,
        -456,
        -1389,
        2178
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Profit before tax from continuing operations",
      "kind": "line",
      "values": [
        10270,
        4764,
        5341,
        4513,
        8505
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Income tax expense",
      "kind": "line",
      "values": [
        -2944,
        -1614,
        -1741,
        -1446,
        -1682
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Profit after tax from continuing operations",
      "kind": "line",
      "values": [
        7326,
        3150,
        3600,
        3068,
        6824
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Attributable to owners of parent",
      "kind": "line",
      "values": [
        7161,
        3124,
        3634,
        3277,
        6429
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Attributable to non-controlling interests",
      "kind": "line",
      "values": [
        165,
        26,
        -33,
        -210,
        395
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Profit (loss) after tax from discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        2363,
        -1359,
        -1447
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Profit after tax",
      "kind": "line",
      "values": [
        7326,
        3150,
        5964,
        1708,
        5376
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Earnings per share, basic (in €) from continuing operations",
      "kind": "line",
      "values": [
        6.14,
        2.68,
        3.11,
        2.8,
        5.45
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Earnings per share, basic (in €)",
      "kind": "line",
      "values": [
        6.14,
        2.68,
        5.26,
        1.95,
        4.46
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Earnings per share, diluted (in €) from continuing operations",
      "kind": "line",
      "values": [
        6.1,
        2.65,
        3.08,
        2.79,
        5.45
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Earnings per share, diluted (in €)",
      "kind": "line",
      "values": [
        6.1,
        2.65,
        5.2,
        1.94,
        4.46
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        1,
        2,
        3
      ]
    }
  ]
}

export const balanceSheet: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022"
  ],
  "rows": [
    {
      "label": "Cash and cash equivalents",
      "kind": "line",
      "values": [
        8220,
        9609,
        8124,
        9008
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Other financial assets",
      "kind": "line",
      "values": [
        1552,
        1629,
        3344,
        853
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Trade and other receivables",
      "kind": "line",
      "values": [
        6675,
        6774,
        6322,
        6236
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Other non-financial assets",
      "kind": "line",
      "values": [
        3212,
        2682,
        2374,
        2139
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Tax assets",
      "kind": "line",
      "values": [
        598,
        707,
        407,
        287
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Total current assets",
      "kind": "total",
      "values": [
        20256,
        21401,
        20571,
        18522
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Goodwill",
      "kind": "line",
      "values": [
        29014,
        31264,
        29081,
        33077
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Intangible assets",
      "kind": "line",
      "values": [
        2282,
        2706,
        2505,
        3835
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Property, plant, and equipment",
      "kind": "line",
      "values": [
        4497,
        4493,
        4276,
        4934
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Deferred tax assets",
      "kind": "line",
      "values": [
        2163,
        2674,
        2197,
        2095
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Total non-current assets",
      "kind": "total",
      "values": [
        50086,
        52836,
        47760,
        53638
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Total assets",
      "kind": "total",
      "values": [
        70362,
        74237,
        68331,
        72159
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Trade and other payables",
      "kind": "line",
      "values": [
        2431,
        1988,
        1783,
        2146
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Tax liabilities",
      "kind": "line",
      "values": [
        968,
        585,
        266,
        283
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Financial liabilities",
      "kind": "line",
      "values": [
        2050,
        4277,
        1735,
        4808
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Other non-financial liabilities",
      "kind": "line",
      "values": [
        4849,
        5537,
        5647,
        4818
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Provisions",
      "kind": "line",
      "values": [
        537,
        716,
        235,
        90
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Contract liabilities",
      "kind": "line",
      "values": [
        6581,
        5978,
        4975,
        5309
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Total current liabilities",
      "kind": "total",
      "values": [
        17416,
        19082,
        14641,
        17453
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Deferred tax liabilities",
      "kind": "line",
      "values": [
        72,
        326,
        267,
        241
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Total non-current liabilities",
      "kind": "total",
      "values": [
        7873,
        9349,
        10284,
        11858
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Total liabilities",
      "kind": "total",
      "values": [
        25288,
        28431,
        24925,
        29311
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Issued capital",
      "kind": "line",
      "values": [
        1229,
        1229,
        1229,
        1229
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Share premium",
      "kind": "line",
      "values": [
        2778,
        2564,
        1845,
        3081
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Retained earnings",
      "kind": "line",
      "values": [
        47345,
        42907,
        42457,
        36418
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Other components of equity",
      "kind": "line",
      "values": [
        182,
        4692,
        2367,
        3801
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Treasury shares",
      "kind": "line",
      "values": [
        -6948,
        -5954,
        -4741,
        -4341
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Equity attributable to owners of parent",
      "kind": "total",
      "values": [
        44586,
        45438,
        43157,
        40186
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Non-controlling interests",
      "kind": "line",
      "values": [
        488,
        368,
        249,
        2662
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Total equity",
      "kind": "total",
      "values": [
        45073,
        45806,
        43406,
        42848
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Total equity and liabilities",
      "kind": "total",
      "values": [
        70362,
        74237,
        68331,
        72159
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2
      ]
    }
  ]
}

export const cashFlowStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021"
  ],
  "rows": [
    {
      "label": "Profit (loss) after tax",
      "kind": "line",
      "values": [
        7326,
        3150,
        5964,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Adjustments to reconcile profit (loss) after tax to net cash flows from operating activities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "(Profit) loss after tax from discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        -2363,
        1359,
        1447
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Depreciation and amortization",
      "kind": "line",
      "values": [
        1311,
        1280,
        1373,
        1569,
        1537
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Share-based payment expense",
      "kind": "line",
      "values": [
        1695,
        2385,
        2220,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Income tax expense",
      "kind": "line",
      "values": [
        2944,
        1614,
        1741,
        1446,
        1682
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Financial income, net",
      "kind": "line",
      "values": [
        -534,
        -398,
        456,
        1389,
        -2178
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Increase/decrease in allowances on trade receivables",
      "kind": "line",
      "values": [
        11,
        30,
        -10,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Other adjustments for non-cash items",
      "kind": "line",
      "values": [
        94,
        110,
        23,
        -175,
        15
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Increase/decrease in trade and other receivables",
      "kind": "line",
      "values": [
        -388,
        -247,
        -393,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Increase/decrease in other assets",
      "kind": "line",
      "values": [
        -1315,
        -632,
        -700,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Increase/decrease in trade payables, provisions, and other liabilities",
      "kind": "line",
      "values": [
        -308,
        603,
        633,
        154,
        429
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Increase/decrease in contract liabilities",
      "kind": "line",
      "values": [
        1336,
        869,
        443,
        643,
        -59
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Share-based payments",
      "kind": "line",
      "values": [
        -817,
        -1282,
        -1091,
        -1180,
        -1056
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Income taxes paid, net of refunds",
      "kind": "line",
      "values": [
        -2198,
        -2277,
        -2161,
        -1642,
        -2047
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net cash flows from operating activities – continuing operations",
      "kind": "subtotal",
      "values": [
        9156,
        5207,
        6134,
        5675,
        6182
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net cash flows from operating activities – discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        113,
        -29,
        41
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net cash flows from operating activities",
      "kind": "total",
      "values": [
        9156,
        5207,
        6246,
        5647,
        6223
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Business combinations, net of cash and cash equivalents acquired",
      "kind": "line",
      "values": [
        -702,
        -1114,
        -1168,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Cash flows from derivative financial instruments related to the sale of subsidiaries or businesses",
      "kind": "line",
      "values": [
        0,
        0,
        -91,
        0,
        0
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Purchase of intangible assets and property, plant, and equipment",
      "kind": "line",
      "values": [
        -739,
        -797,
        -785,
        -877,
        -701
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Proceeds from sales of intangible assets and property, plant, and equipment",
      "kind": "line",
      "values": [
        121,
        122,
        99,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Purchase of equity or debt instruments of other entities",
      "kind": "line",
      "values": [
        -5845,
        -6401,
        -3566,
        -2320,
        -4368
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Proceeds from sales of equity or debt instruments of other entities",
      "kind": "line",
      "values": [
        5779,
        7533,
        907,
        4190,
        3229
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Interest received",
      "kind": "line",
      "values": [
        420,
        563,
        469,
        156,
        56
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net cash flows from investing activities – continuing operations",
      "kind": "subtotal",
      "values": [
        -965,
        -93,
        -4134,
        699,
        -2856
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net cash flows from investing activities – discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        5523,
        -32,
        -208
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net cash flows from investing activities",
      "kind": "total",
      "values": [
        -965,
        -93,
        1389,
        667,
        -3063
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Dividends paid",
      "kind": "line",
      "values": [
        -2743,
        -2565,
        -2395,
        -2865,
        -2182
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Dividends paid on non-controlling interests",
      "kind": "line",
      "values": [
        -2,
        -1,
        -13,
        -12,
        -54
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Purchase of treasury shares",
      "kind": "line",
      "values": [
        -1937,
        -2106,
        -949,
        -1500,
        0
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Proceeds from borrowings",
      "kind": "line",
      "values": [
        2,
        2767,
        13,
        158,
        1680
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Repayments of borrowings",
      "kind": "line",
      "values": [
        -3191,
        -1185,
        -4081,
        -1445,
        -1952
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Payments of lease liabilities",
      "kind": "line",
      "values": [
        -299,
        -310,
        -332,
        -410,
        -375
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Transactions with non-controlling interests",
      "kind": "line",
      "values": [
        0,
        -11,
        0,
        0,
        -2
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Interest paid",
      "kind": "line",
      "values": [
        -574,
        -550,
        -393,
        -244,
        -198
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net cash flows from financing activities – continuing operations",
      "kind": "subtotal",
      "values": [
        -8745,
        -3961,
        -8151,
        -6074,
        -2885
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net cash flows from financing activities – discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        20,
        -263,
        2828
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net cash flows from financing activities",
      "kind": "total",
      "values": [
        -8745,
        -3961,
        -8131,
        -6337,
        -56
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Effect of foreign currency rates on cash and cash equivalents",
      "kind": "line",
      "values": [
        -836,
        333,
        -388,
        134,
        484
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Net increase/decrease in cash and cash equivalents",
      "kind": "line",
      "values": [
        -1390,
        1485,
        -883,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Cash and cash equivalents at the beginning of the period",
      "kind": "line",
      "values": [
        9609,
        8124,
        9008,
        8898,
        5311
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Cash and cash equivalents at the end of the period",
      "kind": "line",
      "values": [
        8220,
        9609,
        8124,
        9008,
        8898
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3
      ]
    },
    {
      "label": "Profit after tax",
      "kind": "line",
      "values": [
        null,
        3150,
        5964,
        1708,
        5376
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3
      ]
    },
    {
      "label": "Adjustments to reconcile profit after tax to net cash flow from operating activities",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Share-based payment expenses",
      "kind": "line",
      "values": [
        null,
        2385,
        2220,
        1431,
        1335
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3
      ]
    },
    {
      "label": "Decrease/increase in allowances on trade receivables",
      "kind": "line",
      "values": [
        null,
        30,
        -10,
        77,
        -9
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3
      ]
    },
    {
      "label": "Decrease/increase in trade and other receivables",
      "kind": "line",
      "values": [
        null,
        -247,
        -393,
        196,
        497
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3
      ]
    },
    {
      "label": "Decrease/increase in other assets",
      "kind": "line",
      "values": [
        null,
        -632,
        -700,
        -1213,
        -645
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3
      ]
    },
    {
      "label": "Cash flows for business combinations, net of cash and cash equivalents acquired",
      "kind": "line",
      "values": [
        null,
        -1114,
        -1168,
        -679,
        -1032
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3
      ]
    },
    {
      "label": "Proceeds from sales of subsidiaries or other businesses",
      "kind": "line",
      "values": [
        null,
        0,
        0,
        289,
        -72
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3
      ]
    },
    {
      "label": "Proceeds from sales of intangible assets or property, plant, and equipment",
      "kind": "line",
      "values": [
        null,
        122,
        99,
        95,
        89
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3
      ]
    },
    {
      "label": "Net decrease/increase in cash and cash equivalents",
      "kind": "line",
      "values": [
        null,
        1485,
        -883,
        109,
        3587
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        3
      ]
    }
  ]
}

export default { incomeStatement, balanceSheet, cashFlowStatement, sources }
