// Generated by crawler/src/extract.ts — do not edit by hand.
import type { StatementData } from "@/lib/types"

// The report PDFs these numbers were extracted from.
export const sources = [
  {
    "year": 2025,
    "url": "https://www.sap.com/docs/download/investors/2025/sap-2025-annual-report-form-20f.pdf"
  },
  {
    "year": 2024,
    "url": "https://www.sap.com/docs/download/investors/2024/sap-2024-integrated-report.pdf"
  },
  {
    "year": 2023,
    "url": "https://www.sap.com/docs/download/investors/2023/sap-2023-annual-report-form-20f.pdf"
  },
  {
    "year": 2022,
    "url": "https://www.sap.com/docs/download/investors/2022/sap-2022-annual-report-form-20f.pdf"
  },
  {
    "year": 2021,
    "url": "https://www.sap.com/docs/download/investors/2021/sap-2021-annual-report-form-20f.pdf"
  },
  {
    "year": 2020,
    "url": "https://www.sap.com/docs/download/investors/2020/sap-2020-annual-report-form-20f.pdf"
  },
  {
    "year": 2019,
    "url": "https://www.sap.com/docs/download/investors/2019/sap-2019-annual-report-form-20f.pdf"
  },
  {
    "year": 2018,
    "url": "https://www.sap.com/docs/download/investors/2018/sap-2018-annual-report-form-20f.pdf"
  },
  {
    "year": 2017,
    "url": "https://www.sap.com/docs/download/investors/2017/sap-2017-annual-report-form-20f.pdf"
  },
  {
    "year": 2016,
    "url": "https://www.sap.com/docs/download/investors/2016/sap-2016-annual-report-form-20f.pdf"
  }
]

// Cross-statement validation result (accounting identities) at extraction time.
export const validation = {
  "status": "pass",
  "issues": []
} as const

export const incomeStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014"
  ],
  "rows": [
    {
      "label": "Cloud",
      "kind": "line",
      "values": [
        21023,
        17141,
        13664,
        11426,
        8701,
        8080,
        6933,
        4993,
        3769,
        null,
        null,
        null
      ],
      "restatedIndices": [
        3,
        4
      ]
    },
    {
      "label": "Software licenses",
      "kind": "line",
      "values": [
        990,
        1399,
        1764,
        2056,
        3248,
        3642,
        4533,
        4647,
        4872,
        4859,
        4835,
        4399
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Software support",
      "kind": "line",
      "values": [
        10525,
        11290,
        11496,
        11909,
        11412,
        11506,
        11547,
        10981,
        10908,
        10571,
        10093,
        8829
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Software licenses and support",
      "kind": "line",
      "values": [
        11515,
        12689,
        13261,
        13965,
        14660,
        15148,
        16080,
        15628,
        15780,
        15431,
        14928,
        13228
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Cloud and software",
      "kind": "line",
      "values": [
        32538,
        29830,
        26924,
        25391,
        23361,
        23228,
        23012,
        20622,
        19549,
        18424,
        17214,
        14315
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Services",
      "kind": "line",
      "values": [
        4262,
        4346,
        4283,
        4128,
        3592,
        4110,
        4541,
        4086,
        3912,
        3639,
        3579,
        3245
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Total revenue",
      "kind": "total",
      "values": [
        36800,
        34176,
        31207,
        29520,
        26953,
        27338,
        27553,
        24708,
        23461,
        22062,
        20793,
        17560
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Cost of cloud",
      "kind": "line",
      "values": [
        -5480,
        -4660,
        -3884,
        -3499,
        -2881,
        -2699,
        -2534,
        -2068,
        -1660,
        null,
        null,
        null
      ],
      "restatedIndices": [
        3,
        4
      ]
    },
    {
      "label": "Cost of software licenses and support",
      "kind": "line",
      "values": [
        -1313,
        -1262,
        -1383,
        -1384,
        -1598,
        -2008,
        -2159,
        -2092,
        -2234,
        -2182,
        -2291,
        -2076
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Cost of cloud and software",
      "kind": "line",
      "values": [
        -6793,
        -5922,
        -5267,
        -4883,
        -4479,
        -4707,
        -4692,
        -4160,
        -3893,
        -3495,
        -3313,
        -2557
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Cost of services",
      "kind": "line",
      "values": [
        -3193,
        -3321,
        -3407,
        -3155,
        -2740,
        -3178,
        -3662,
        -3302,
        -3158,
        -3089,
        -2932,
        -2426
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Total cost of revenue",
      "kind": "total",
      "values": [
        -9986,
        -9243,
        -8674,
        -8038,
        -7219,
        -7886,
        -8355,
        -7462,
        -7051,
        -6583,
        -6245,
        -4983
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Gross profit",
      "kind": "line",
      "values": [
        26814,
        24932,
        22534,
        21482,
        19734,
        19453,
        19199,
        17246,
        16410,
        15479,
        14548,
        12578
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Research and development",
      "kind": "line",
      "values": [
        -6633,
        -6514,
        -6324,
        -6080,
        -5270,
        -4454,
        -4292,
        -3624,
        -3352,
        -3044,
        -2845,
        -2331
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Sales and marketing",
      "kind": "line",
      "values": [
        -8879,
        -9090,
        -8828,
        -7946,
        -6856,
        -7106,
        -7693,
        -6781,
        -6924,
        -6265,
        -5782,
        -4593
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "General and administration",
      "kind": "line",
      "values": [
        -1633,
        -1435,
        -1364,
        -1289,
        -1187,
        -1356,
        -1629,
        -1098,
        -1075,
        -1005,
        -1048,
        -892
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Restructuring",
      "kind": "line",
      "values": [
        -3,
        -3144,
        -215,
        -138,
        -157,
        3,
        -1130,
        -19,
        -182,
        -28,
        -621,
        -126
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Other operating income/expense, net",
      "kind": "line",
      "values": [
        -49,
        -85,
        -4,
        60,
        44,
        84,
        18,
        -20,
        1,
        -3,
        1,
        -4
      ],
      "restatedIndices": [
        2,
        3,
        4,
        9,
        10
      ]
    },
    {
      "label": "Total operating expenses",
      "kind": "total",
      "values": [
        -27183,
        -29511,
        -25408,
        -23429,
        -20645,
        -20715,
        -23081,
        -19005,
        -18584,
        -16928,
        -16541,
        -13230
      ],
      "restatedIndices": [
        2,
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Operating profit",
      "kind": "line",
      "values": [
        9617,
        4665,
        5799,
        6090,
        6308,
        6623,
        4473,
        5703,
        4877,
        5135,
        4252,
        4331
      ],
      "restatedIndices": [
        2,
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Other non-operating income/expense, net",
      "kind": "line",
      "values": [
        118,
        -298,
        -3,
        -187,
        19,
        -179,
        -74,
        -56,
        -36,
        -234,
        -256,
        -49
      ],
      "restatedIndices": [
        2,
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Finance income",
      "kind": "line",
      "values": [
        1911,
        1429,
        857,
        811,
        3123,
        1473,
        787,
        371,
        476,
        230,
        241,
        127
      ],
      "restatedIndices": [
        3,
        8,
        9
      ]
    },
    {
      "label": "Finance costs",
      "kind": "line",
      "values": [
        -1377,
        -1031,
        -1313,
        -2200,
        -945,
        -697,
        -589,
        -418,
        -288,
        -259,
        -246,
        -152
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Financial income, net",
      "kind": "line",
      "values": [
        534,
        398,
        -456,
        -1389,
        2178,
        776,
        198,
        -47,
        188,
        -29,
        -5,
        -25
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Profit before tax from continuing operations",
      "kind": "line",
      "values": [
        10270,
        4764,
        5341,
        4513,
        8505,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Income tax expense",
      "kind": "line",
      "values": [
        -2944,
        -1614,
        -1741,
        -1446,
        -1682,
        -1938,
        -1226,
        -1511,
        -983,
        -1242,
        -935,
        -1075
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Profit after tax from continuing operations",
      "kind": "line",
      "values": [
        7326,
        3150,
        3600,
        3068,
        6824,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Attributable to owners of parent",
      "kind": "line",
      "values": [
        7161,
        3124,
        3634,
        3277,
        6429,
        5145,
        3321,
        4083,
        4008,
        3642,
        3064,
        3280
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Attributable to non-controlling interests",
      "kind": "line",
      "values": [
        165,
        26,
        -33,
        -210,
        395,
        138,
        50,
        6,
        38,
        -13,
        -8,
        0
      ],
      "restatedIndices": [
        3,
        4,
        8
      ]
    },
    {
      "label": "Profit (loss) after tax from discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        2363,
        -1359,
        -1447,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Profit after tax",
      "kind": "line",
      "values": [
        7326,
        3150,
        5964,
        1708,
        5376,
        5283,
        3370,
        4088,
        4046,
        3629,
        3056,
        3280
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Attributable to owners of parent",
      "kind": "line",
      "values": [
        7161,
        3124,
        6139,
        2284,
        5256,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Attributable to non-controlling interests",
      "kind": "line",
      "values": [
        165,
        26,
        -175,
        -576,
        121,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Earnings per share, basic (in €) from continuing operations",
      "kind": "line",
      "values": [
        6.14,
        2.68,
        3.11,
        2.8,
        5.45,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "decimals": 2
    },
    {
      "label": "Earnings per share, basic (in €)1",
      "kind": "line",
      "values": [
        6.14,
        2.68,
        5.26,
        1.95,
        4.46,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "decimals": 2
    },
    {
      "label": "Earnings per share, diluted (in €) from continuing operations",
      "kind": "line",
      "values": [
        6.1,
        2.65,
        3.08,
        2.79,
        5.45,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "decimals": 2
    },
    {
      "label": "Earnings per share, diluted (in €)1",
      "kind": "line",
      "values": [
        6.1,
        2.65,
        5.2,
        1.94,
        4.46,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "decimals": 2
    },
    {
      "label": "Consolidated Income Statements of SAP Group for the Years Ended December 31",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Cost of Revenue",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Operating Expenses",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Research and Development Expenses",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Sales and Marketing Expenses",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "General and Administrative Expenses",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Operating Income",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Other Income/Expenses, Net",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Income Before Taxes",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Income Taxes",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Net Income",
      "kind": "total",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Profit before tax",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        3090,
        6847,
        7220,
        4596,
        5600,
        5029,
        4872,
        3991,
        4355
      ],
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Earnings per share, basic (in €)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        1.95,
        4.46,
        4.35,
        2.78,
        3.42,
        3.35,
        3.04,
        2.56,
        2.75
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        9
      ],
      "historical": true
    },
    {
      "label": "Earnings per share, diluted (in €)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        1.94,
        4.46,
        4.35,
        2.78,
        3.42,
        3.35,
        3.04,
        2.56,
        2.74
      ],
      "unit": "currency",
      "decimals": 2,
      "restatedIndices": [
        9
      ],
      "historical": true
    },
    {
      "label": "Cloud subscriptions and support",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        4993,
        3769,
        2993,
        2286,
        1087
      ],
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Cost of cloud subscriptions and support",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -2068,
        -1660,
        -1313,
        -1022,
        -481
      ],
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Earnings per share, basic (in respective currency)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        4.03,
        3.04,
        2.56,
        null
      ],
      "unit": "currency",
      "decimals": 2,
      "historical": true
    },
    {
      "label": "Earnings per share, diluted (in respective currency)",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        4.03,
        3.04,
        2.56,
        null
      ],
      "unit": "currency",
      "decimals": 2,
      "historical": true
    },
    {
      "label": "TomorrowNow and Versata litigation",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        -309
      ],
      "historical": true
    },
    {
      "label": "Income tax TomorrowNow and Versata litigation",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        -86
      ],
      "historical": true
    },
    {
      "label": "Other income tax expense",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -1297,
        -935,
        -1161
      ],
      "historical": true
    }
  ]
}

export const balanceSheet: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015"
  ],
  "rows": [
    {
      "label": "Cash and cash equivalents",
      "kind": "line",
      "values": [
        8220,
        9609,
        8124,
        9008,
        8898,
        5311,
        5314,
        8627,
        4011,
        3702,
        3411
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Other financial assets",
      "kind": "line",
      "values": [
        1552,
        1629,
        3344,
        853,
        2758,
        1635,
        297,
        448,
        990,
        990,
        1124
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Trade and other receivables",
      "kind": "line",
      "values": [
        6675,
        6774,
        6322,
        6236,
        6352,
        6593,
        7908,
        6362,
        5899,
        5924,
        5274
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Other non-financial assets",
      "kind": "line",
      "values": [
        3212,
        2682,
        2374,
        2139,
        1633,
        1321,
        1188,
        889,
        725,
        581,
        468
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Tax assets",
      "kind": "line",
      "values": [
        598,
        707,
        407,
        287,
        403,
        210,
        506,
        293,
        306,
        233,
        235
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Total current assets",
      "kind": "total",
      "values": [
        20256,
        21401,
        20571,
        18522,
        20044,
        15069,
        15213,
        16620,
        11930,
        11564,
        9739
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Goodwill",
      "kind": "line",
      "values": [
        29014,
        31264,
        29081,
        33077,
        31089,
        27538,
        29159,
        23736,
        21271,
        23311,
        22689
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Intangible assets",
      "kind": "line",
      "values": [
        2282,
        2706,
        2505,
        3835,
        3965,
        3784,
        4491,
        3227,
        2967,
        3786,
        4280
      ],
      "unit": "currency",
      "restatedIndices": [
        4,
        8,
        9
      ]
    },
    {
      "label": "Property, plant, and equipment",
      "kind": "line",
      "values": [
        4497,
        4493,
        4276,
        4934,
        4977,
        5041,
        5496,
        3553,
        2967,
        2580,
        2192
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Other financial assets",
      "kind": "line",
      "values": [
        7269,
        7141,
        5543,
        5626,
        6275,
        3512,
        2336,
        1536,
        1155,
        1358,
        1336
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Trade and other receivables",
      "kind": "line",
      "values": [
        218,
        209,
        203,
        169,
        147,
        137,
        129,
        118,
        118,
        126,
        87
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Other non-financial assets",
      "kind": "line",
      "values": [
        4419,
        3990,
        3573,
        3580,
        2628,
        1926,
        1701,
        1301,
        687,
        532,
        332
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Tax assets",
      "kind": "line",
      "values": [
        244,
        359,
        382,
        323,
        263,
        271,
        435,
        397,
        352,
        450,
        282
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Deferred tax assets",
      "kind": "line",
      "values": [
        2163,
        2674,
        2197,
        2095,
        1786,
        1188,
        1251,
        1014,
        1037,
        571,
        453
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        3,
        4,
        5,
        7,
        8,
        9
      ]
    },
    {
      "label": "Total non-current assets",
      "kind": "total",
      "values": [
        50106,
        52836,
        47760,
        53638,
        51130,
        43395,
        44999,
        34881,
        30554,
        32713,
        31651
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Total assets",
      "kind": "total",
      "values": [
        70362,
        74237,
        68331,
        72159,
        71174,
        58464,
        60212,
        51502,
        42484,
        44277,
        41390
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Trade and other payables",
      "kind": "line",
      "values": [
        2431,
        1988,
        1783,
        2146,
        1580,
        1367,
        1581,
        1491,
        1151,
        1281,
        1088
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        5,
        7,
        8,
        9
      ]
    },
    {
      "label": "Tax liabilities",
      "kind": "line",
      "values": [
        968,
        585,
        266,
        283,
        304,
        414,
        255,
        611,
        597,
        316,
        230
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Financial liabilities",
      "kind": "line",
      "values": [
        2050,
        4277,
        1735,
        4808,
        4528,
        2348,
        3273,
        1125,
        1561,
        1813,
        841
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Other non-financial liabilities",
      "kind": "line",
      "values": [
        4849,
        5537,
        5647,
        4818,
        5203,
        4643,
        4839,
        4120,
        3982,
        3699,
        3407
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        6,
        8,
        9
      ]
    },
    {
      "label": "Provisions",
      "kind": "line",
      "values": [
        537,
        716,
        235,
        90,
        89,
        73,
        247,
        110,
        149,
        183,
        299
      ],
      "unit": "currency",
      "restatedIndices": [
        6,
        8,
        9
      ]
    },
    {
      "label": "Contract liabilities",
      "kind": "line",
      "values": [
        6581,
        5978,
        4975,
        5309,
        4431,
        3996,
        4266,
        3028,
        null,
        null,
        null
      ],
      "unit": "currency",
      "restatedIndices": [
        5
      ]
    },
    {
      "label": "Total current liabilities",
      "kind": "total",
      "values": [
        17416,
        19082,
        14641,
        17453,
        16136,
        12842,
        14462,
        10486,
        10210,
        9674,
        7867
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        7,
        8,
        9
      ]
    },
    {
      "label": "Trade and other payables",
      "kind": "line",
      "values": [
        2,
        10,
        39,
        79,
        122,
        98,
        8,
        129,
        119,
        127,
        81
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Tax liabilities",
      "kind": "line",
      "values": [
        562,
        512,
        874,
        893,
        827,
        667,
        538,
        495,
        434,
        365,
        402
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        8,
        9
      ]
    },
    {
      "label": "Financial liabilities",
      "kind": "line",
      "values": [
        6021,
        7169,
        7941,
        9547,
        11042,
        13605,
        12923,
        10553,
        5034,
        6481,
        8681
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Other non-financial liabilities",
      "kind": "line",
      "values": [
        524,
        749,
        698,
        705,
        860,
        770,
        957,
        501,
        514,
        461,
        331
      ],
      "unit": "currency",
      "restatedIndices": [
        6,
        8,
        9
      ]
    },
    {
      "label": "Provisions",
      "kind": "line",
      "values": [
        550,
        494,
        432,
        359,
        355,
        362,
        335,
        270,
        328,
        217,
        180
      ],
      "unit": "currency",
      "restatedIndices": [
        2,
        5,
        6,
        8,
        9
      ]
    },
    {
      "label": "Deferred tax liabilities",
      "kind": "line",
      "values": [
        72,
        326,
        267,
        241,
        296,
        158,
        79,
        102,
        251,
        411,
        448
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        4,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Contract liabilities",
      "kind": "line",
      "values": [
        144,
        88,
        33,
        33,
        13,
        36,
        89,
        88,
        null,
        null,
        null
      ],
      "unit": "currency"
    },
    {
      "label": "Total non-current liabilities",
      "kind": "total",
      "values": [
        7873,
        9349,
        10284,
        11858,
        13515,
        15696,
        14929,
        12138,
        6759,
        8205,
        10228
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Total liabilities",
      "kind": "total",
      "values": [
        25288,
        28431,
        24925,
        29311,
        29651,
        28537,
        29390,
        22624,
        16969,
        17880,
        18095
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Issued capital",
      "kind": "line",
      "values": [
        1229,
        1229,
        1229,
        1229,
        1229,
        1229,
        1229,
        1229,
        1229,
        1229,
        1229
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Share premium",
      "kind": "line",
      "values": [
        2778,
        2564,
        1845,
        3081,
        1918,
        545,
        545,
        543,
        570,
        599,
        558
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Retained earnings",
      "kind": "line",
      "values": [
        47345,
        42907,
        42457,
        36418,
        37022,
        32026,
        28783,
        27407,
        24769,
        22302,
        20044
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Other components of equity",
      "kind": "line",
      "values": [
        182,
        4692,
        2367,
        3801,
        1756,
        -1012,
        1770,
        1234,
        508,
        3346,
        2561
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        4,
        5,
        8,
        9
      ]
    },
    {
      "label": "Treasury shares",
      "kind": "line",
      "values": [
        -6948,
        -5954,
        -4741,
        -4341,
        -3072,
        -3072,
        -1580,
        -1580,
        -1591,
        -1099,
        -1124
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Equity attributable to owners of parent",
      "kind": "line",
      "values": [
        44586,
        45438,
        43157,
        40186,
        38853,
        29716,
        30746,
        28832,
        25484,
        26376,
        23267
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        5,
        8,
        9
      ]
    },
    {
      "label": "Non-controlling interests",
      "kind": "line",
      "values": [
        488,
        368,
        249,
        2662,
        2670,
        211,
        76,
        45,
        31,
        21,
        28
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Total equity",
      "kind": "total",
      "values": [
        45073,
        45806,
        43406,
        42848,
        41523,
        29927,
        30822,
        28877,
        25515,
        26397,
        23295
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        5,
        8,
        9
      ]
    },
    {
      "label": "Total equity and liabilities",
      "kind": "total",
      "values": [
        70362,
        74237,
        68331,
        72159,
        71174,
        58464,
        60212,
        51502,
        42484,
        44277,
        41390
      ],
      "unit": "currency",
      "restatedIndices": [
        1,
        2,
        4,
        5,
        6,
        7,
        8,
        9
      ]
    },
    {
      "label": "Contract liabilities/deferred income",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        3028,
        2771,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Contract liabilities/deferred income",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        88,
        79,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Deferred income",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        3331,
        2383,
        2001
      ],
      "restatedIndices": [
        9
      ],
      "historical": true
    },
    {
      "label": "Deferred income",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        95,
        143,
        106
      ],
      "restatedIndices": [
        9
      ],
      "historical": true
    }
  ]
}

export const cashFlowStatement: StatementData = {
  "periods": [
    "2025",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
    "2016",
    "2015",
    "2014"
  ],
  "rows": [
    {
      "label": "Profit (loss) after tax",
      "kind": "line",
      "values": [
        7326,
        3150,
        5964,
        1708,
        5376,
        5283,
        3370,
        4088,
        4046,
        3629,
        3056,
        3280
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Adjustments to reconcile profit (loss) after tax to net cash flows from operating activities:",
      "kind": "section",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "(Profit) loss after tax from discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        -2363,
        1359,
        1447,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Depreciation and amortization–",
      "kind": "line",
      "values": [
        1311,
        1280,
        1373,
        1569,
        1537,
        1831,
        1872,
        1362,
        1272,
        1268,
        1268,
        1289
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Share-based payment expense",
      "kind": "line",
      "values": [
        1695,
        2385,
        2220,
        1431,
        1335,
        1084,
        1835,
        830,
        1120,
        null,
        null,
        null
      ],
      "restatedIndices": [
        3,
        4
      ]
    },
    {
      "label": "Income tax expense",
      "kind": "line",
      "values": [
        2944,
        1614,
        1741,
        1446,
        1682,
        1938,
        1226,
        1511,
        983,
        1242,
        1229,
        1075
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9,
        10
      ]
    },
    {
      "label": "Financial income, net",
      "kind": "line",
      "values": [
        -534,
        -398,
        456,
        1389,
        -2178,
        -776,
        -198,
        47,
        -188,
        29,
        5,
        25
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Increase/decrease in allowances on trade receivables",
      "kind": "line",
      "values": [
        11,
        30,
        -10,
        77,
        -9,
        68,
        14,
        -67,
        -32,
        null,
        null,
        null
      ],
      "restatedIndices": [
        3,
        4
      ]
    },
    {
      "label": "Other adjustments for non-cash items",
      "kind": "line",
      "values": [
        94,
        110,
        23,
        -175,
        15,
        -198,
        -54,
        3,
        -9,
        39,
        -2,
        70
      ],
      "restatedIndices": [
        3,
        4,
        7,
        8,
        9
      ]
    },
    {
      "label": "Increase/decrease in trade and other receivables",
      "kind": "line",
      "values": [
        -388,
        -247,
        -393,
        196,
        497,
        821,
        -1469,
        136,
        -309,
        -675,
        -844,
        -286
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Increase/decrease in other assets",
      "kind": "line",
      "values": [
        -1315,
        -632,
        -700,
        -1213,
        -645,
        -651,
        -583,
        -477,
        -325,
        -248,
        -313,
        -329
      ],
      "restatedIndices": [
        3,
        4,
        7,
        8,
        9
      ]
    },
    {
      "label": "Increase/decrease in trade payables, provisions, and other liabilities",
      "kind": "line",
      "values": [
        -308,
        603,
        633,
        154,
        429,
        293,
        328,
        240,
        63,
        513,
        757,
        573
      ],
      "restatedIndices": [
        3,
        4,
        7,
        8,
        9
      ]
    },
    {
      "label": "Increase/decrease in contract liabilities",
      "kind": "line",
      "values": [
        1336,
        869,
        443,
        643,
        -59,
        128,
        984,
        -561,
        718,
        null,
        null,
        null
      ],
      "restatedIndices": [
        3,
        4
      ]
    },
    {
      "label": "Share-based payments",
      "kind": "line",
      "values": [
        -817,
        -1282,
        -1091,
        -1180,
        -1056,
        -1310,
        -1257,
        -971,
        -849,
        null,
        null,
        null
      ],
      "restatedIndices": [
        3,
        4
      ]
    },
    {
      "label": "Income taxes paid, net of refunds",
      "kind": "line",
      "values": [
        -2198,
        -2277,
        -2161,
        -1642,
        -2047,
        -1194,
        -2329,
        -1687,
        -1332,
        -1477,
        -1420,
        -1356
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Net cash flows from operating activities – continuing operations",
      "kind": "line",
      "values": [
        9156,
        5207,
        6134,
        5675,
        6182,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Net cash flows from operating activities – discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        113,
        -29,
        41,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        2
      ]
    },
    {
      "label": "Net cash flows from operating activities",
      "kind": "total",
      "values": [
        9156,
        5207,
        6246,
        5647,
        6223,
        7194,
        3496,
        4303,
        5045,
        4628,
        3638,
        3499
      ],
      "restatedIndices": [
        1,
        2,
        8,
        9
      ]
    },
    {
      "label": "Business combinations, net of cash and cash equivalents acquired",
      "kind": "line",
      "values": [
        -702,
        -1114,
        -1168,
        null,
        null,
        null,
        null,
        -2036,
        -291,
        -106,
        -39,
        -6360
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Cash flows from derivative financial instruments related to the sale of subsidiaries or businesses",
      "kind": "line",
      "values": [
        0,
        0,
        -91,
        0,
        0,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Purchase of intangible assets and property, plant, and equipment",
      "kind": "line",
      "values": [
        -739,
        -797,
        -785,
        -877,
        -701,
        -816,
        -817,
        -1458,
        -1275,
        -1001,
        -636,
        -737
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Proceeds from sales of intangible assets and property, plant, and equipment",
      "kind": "line",
      "values": [
        121,
        122,
        99,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    {
      "label": "Purchase of equity or debt instruments of other entities",
      "kind": "line",
      "values": [
        -5845,
        -6401,
        -3566,
        -2320,
        -4368,
        -2535,
        -900,
        -1013,
        -2914,
        -1549,
        -1871,
        -910
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Proceeds from sales of equity or debt instruments of other entities",
      "kind": "line",
      "values": [
        5779,
        7533,
        907,
        4190,
        3229,
        735,
        778,
        1488,
        3272,
        793,
        1880,
        833
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Interest received",
      "kind": "line",
      "values": [
        420,
        563,
        469,
        156,
        56,
        122,
        97,
        99,
        88,
        79,
        82,
        59
      ],
      "restatedIndices": [
        3,
        8,
        9
      ]
    },
    {
      "label": "Net cash flows from investing activities – continuing operations",
      "kind": "line",
      "values": [
        -965,
        -93,
        -4134,
        699,
        -2856,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Net cash flows from investing activities – discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        5523,
        -32,
        -208,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        2
      ]
    },
    {
      "label": "Net cash flows from investing activities",
      "kind": "total",
      "values": [
        -965,
        -93,
        1389,
        667,
        -3063,
        -2986,
        -7021,
        -3066,
        -1112,
        -1799,
        -334,
        -7240
      ],
      "restatedIndices": [
        1,
        2,
        8,
        9
      ]
    },
    {
      "label": "Dividends paid",
      "kind": "line",
      "values": [
        -2743,
        -2565,
        -2395,
        -2865,
        -2182,
        -1864,
        -1790,
        -1671,
        -1499,
        -1378,
        -1316,
        -1194
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Dividends paid on non-controlling interests",
      "kind": "line",
      "values": [
        -2,
        -1,
        -13,
        -12,
        -54,
        -2,
        -17,
        -7,
        -45,
        0,
        0,
        null
      ],
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Purchase of treasury shares",
      "kind": "line",
      "values": [
        -1937,
        -2106,
        -949,
        -1500,
        0,
        -1492,
        0,
        0,
        -500,
        0,
        0,
        null
      ],
      "restatedIndices": [
        8
      ]
    },
    {
      "label": "Proceeds from borrowings",
      "kind": "line",
      "values": [
        2,
        2767,
        13,
        158,
        1680,
        2132,
        3622,
        6368,
        27,
        443,
        1748,
        7503
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Repayments of borrowings",
      "kind": "line",
      "values": [
        -3191,
        -1185,
        -4081,
        -1445,
        -1952,
        -2430,
        -1309,
        -1407,
        -1391,
        -1800,
        -3852,
        -2062
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Payments of lease liabilities",
      "kind": "line",
      "values": [
        -299,
        -310,
        -332,
        -410,
        -375,
        -378,
        -403,
        0,
        0,
        null,
        null,
        null
      ],
      "restatedIndices": [
        3,
        4
      ]
    },
    {
      "label": "Transactions with non-controlling interests",
      "kind": "line",
      "values": [
        0,
        -11,
        0,
        0,
        -2,
        -59,
        0,
        0,
        2,
        3,
        0,
        0
      ]
    },
    {
      "label": "Interest paid",
      "kind": "line",
      "values": [
        -574,
        -550,
        -393,
        -244,
        -198,
        -244,
        -341,
        -251,
        -200,
        -190,
        -172,
        -130
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ]
    },
    {
      "label": "Net cash flows from financing activities – continuing operations",
      "kind": "line",
      "values": [
        -8745,
        -3961,
        -8151,
        -6074,
        -2885,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        1,
        2
      ]
    },
    {
      "label": "Net cash flows from financing activities – discontinued operations",
      "kind": "line",
      "values": [
        0,
        0,
        20,
        -263,
        2828,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "restatedIndices": [
        2
      ]
    },
    {
      "label": "Net cash flows from financing activities",
      "kind": "total",
      "values": [
        -8745,
        -3961,
        -8131,
        -6337,
        -56,
        -3997,
        102,
        3283,
        -3406,
        -2705,
        -3356,
        4298
      ],
      "restatedIndices": [
        1,
        2,
        8,
        9
      ]
    },
    {
      "label": "Effect of foreign currency rates on cash and cash equivalents",
      "kind": "line",
      "values": [
        -836,
        333,
        -388,
        134,
        484,
        -214,
        110,
        97,
        -218,
        167,
        135,
        23
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Net increase/decrease in cash and cash equivalents",
      "kind": "line",
      "values": [
        -1390,
        1485,
        -883,
        109,
        3587,
        -4,
        -3313,
        4617,
        309,
        291,
        83,
        580
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Cash and cash equivalents at the beginning of the period",
      "kind": "line",
      "values": [
        9609,
        8124,
        9008,
        8898,
        5311,
        5314,
        8627,
        4011,
        3702,
        3411,
        3328,
        2748
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Cash and cash equivalents at the end of the period",
      "kind": "line",
      "values": [
        8220,
        9609,
        8124,
        9008,
        8898,
        5311,
        5314,
        8627,
        4011,
        3702,
        3411,
        3328
      ],
      "restatedIndices": [
        8,
        9
      ]
    },
    {
      "label": "Cash flows for business combinations, net of cash and cash equivalents acquired",
      "kind": "line",
      "values": [
        null,
        -1114,
        -1168,
        -679,
        -1032,
        -662,
        -6215,
        -2140,
        -291,
        null,
        null,
        null
      ],
      "restatedIndices": [
        4
      ],
      "historical": true
    },
    {
      "label": "Proceeds from sales of subsidiaries or other businesses",
      "kind": "line",
      "values": [
        null,
        0,
        0,
        289,
        -72,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "historical": true
    },
    {
      "label": "Proceeds from sales of intangible assets or property, plant, and equipment",
      "kind": "line",
      "values": [
        null,
        122,
        99,
        95,
        89,
        88,
        71,
        57,
        97,
        63,
        68,
        46
      ],
      "restatedIndices": [
        3,
        4,
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Cash flows from sale of subsidiaries or businesses",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        289,
        -72,
        203,
        61,
        null,
        null,
        null,
        null,
        null
      ],
      "historical": true
    },
    {
      "label": "Proceeds from changes in ownership interests in subsidiaries that do not result in the loss of control",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        33,
        2828,
        95,
        0,
        0,
        null,
        null,
        null,
        null
      ],
      "historical": true
    },
    {
      "label": "Payments for taxes related to net share settlement of equity awards",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        -282,
        0,
        0,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "historical": true
    },
    {
      "label": "Proceeds from sale of subsidiaries or businesses",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        203,
        61,
        0,
        0,
        null,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Decrease/increase in sales and bad debt allowances on trade receivables",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -67,
        -32,
        51,
        45,
        47
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Decrease/increase in contract liabilities/deferred income",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -561,
        718,
        368,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Cash flows from derivative financial instruments related to business combinations",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -103,
        0,
        0,
        null,
        null
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Total cash flows for business combinations, net of cash and cash equivalents acquired",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        -2140,
        -291,
        -106,
        226,
        -6472
      ],
      "unit": "currency",
      "restatedIndices": [
        8,
        9
      ],
      "historical": true
    },
    {
      "label": "Proceeds from reissuance of treasury shares",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        27,
        64,
        51
      ],
      "unit": "currency",
      "restatedIndices": [
        9
      ],
      "historical": true
    },
    {
      "label": "Decrease/increase in deferred income",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        863,
        368,
        218,
        16
      ],
      "unit": "currency",
      "restatedIndices": [
        9
      ],
      "historical": true
    },
    {
      "label": "Cash receipts from derivative financial instruments related to business combinations",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        266,
        -111
      ],
      "unit": "currency",
      "historical": true
    },
    {
      "label": "Cash receipts from swap contracts",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        43,
        0,
        0
      ],
      "unit": "currency",
      "restatedIndices": [
        9
      ],
      "historical": true
    },
    {
      "label": "Total cash flows from proceeds from borrowings",
      "kind": "subtotal",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        33,
        443,
        1748,
        7503
      ],
      "unit": "currency",
      "restatedIndices": [
        9
      ],
      "historical": true
    },
    {
      "label": "Cash outflows due to TomorrowNow and Versata litigation",
      "kind": "line",
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        0,
        0,
        -555
      ],
      "historical": true
    }
  ]
}

export default { incomeStatement, balanceSheet, cashFlowStatement, sources, validation }
